import {
  RUNNER_LINEAGE_BY_SHAPE_ID,
  type RunnerContractLineage,
} from "./runner-lineage";

export type DataShapeScope = "global" | "namespace" | "organization" | "project" | "run" | "external";
export type DataShapeFormat = "json" | "jsonl" | "key-value" | "sqlite" | "text" | "mixed";
export type DataShapeAssurance = "enforced" | "drift-checked" | "typed" | "observed" | "open";
export type DataShapeRoot = "global" | "namespace" | "organization" | "project";

export interface DataShapeSampleSpec {
  root: DataShapeRoot;
  patterns: string[][];
  excludePatterns?: string[][];
  format: Exclude<DataShapeFormat, "mixed">;
  valuePath?: string;
  schemaPointer?: string;
}

export interface DataShapeDefinition {
  id: string;
  name: string;
  category: "core" | "runner" | "work" | "configuration" | "integrations" | "organization" | "system";
  description: string;
  scope: DataShapeScope;
  format: DataShapeFormat;
  storage: string[];
  assurance: DataShapeAssurance;
  schemaPath?: string;
  typePaths?: string[];
  validatorPaths?: string[];
  writers: string[];
  readers: string[];
  samples?: DataShapeSampleSpec;
  sensitive?: boolean;
  notes?: string[];
  runnerLineage?: RunnerContractLineage;
}

function shape(definition: DataShapeDefinition): DataShapeDefinition {
  const runnerLineage = RUNNER_LINEAGE_BY_SHAPE_ID[definition.id];
  return runnerLineage ? { ...definition, runnerLineage } : definition;
}

export const DATA_SHAPE_CATALOG_VERSION = 2;

/**
 * The registry covers persisted server/runtime data. Browser-only Zustand and
 * localStorage state is deliberately outside this catalog.
 *
 * Storage paths describe the code's actual current behavior. Some project data
 * still lands at namespace scope; those mismatches are stated instead of being
 * rewritten into the intended hierarchy.
 */
export const DATA_SHAPE_CATALOG: DataShapeDefinition[] = [
  shape({
    id: "chain-definition",
    name: "Chain Definition",
    category: "core",
    description: "Agent graph, routing, profiles, and execution configuration consumed by both runners.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/chains/{chainId}/chain.json", "{orgRoot}/chains/{chainId}/.git-backup/chain.json.{timestamp}", "{runRoot}/{runId}/chain.json (execution snapshot)"],
    assurance: "enforced",
    schemaPath: "lib/schemas/chain.schema.json",
    typePaths: ["web/lib/schemas.ts", "web/lib/types.ts"],
    validatorPaths: ["web/lib/validators.ts", "web/app/api/chains/validate/route.ts"],
    writers: [
      "web/app/api/chains/save/route.ts",
      "web/lib/chains/chains-store.ts",
      "web/lib/runs/chain-run-service.ts",
      "web/app/api/chains/[id]/duplicate/route.ts",
      "web/app/api/chains/[id]/git/revert/route.ts",
      "web/app/api/chains/[id]/route.ts",
      "web/app/api/chains/[id]/versions/restore/route.ts",
      "web/app/api/chains/import/route.ts",
      "web/app/api/events/triggers/[id]/route.ts",
      "web/app/api/events/triggers/route.ts",
      "web/app/api/mentiko-mcp/ops/chains/route.ts",
      "web/lib/chains/chain-postprocessor.ts",
      "web/lib/chains/core-chain-installer.ts",
    ],
    readers: ["lib/chain-runner.sh", "web/lib/runs/chain-run-service.ts", "web/lib/runner-v2/completion-entrypoint.ts"],
    samples: { root: "organization", patterns: [["chains", "*", "chain.json"]], format: "json" },
  }),
  shape({
    id: "agent-definition",
    name: "Agent Definition",
    category: "core",
    description: "Reusable agent prompt, trigger, emit, retry, monitor, and profile configuration.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/agents/{agentId}/agent.json"],
    assurance: "enforced",
    schemaPath: "lib/schemas/agent.schema.json",
    typePaths: ["web/lib/schemas.ts", "web/lib/types.ts"],
    validatorPaths: ["web/lib/validators.ts", "web/app/api/validate/route.ts"],
    writers: [
      "web/lib/agents/agents-store.ts",
      "web/app/api/agents/route.ts",
      "web/app/api/agents/registry/[id]/route.ts",
      "web/app/api/agents/registry/import/route.ts",
      "web/app/api/agents/registry/save/route.ts",
      "web/app/api/agents/marketplace/[id]/install/route.ts",
      "web/app/api/agents/marketplace/install/route.ts",
      "web/app/api/mentiko-mcp/ops/agents/route.ts",
    ],
    readers: ["web/lib/agents/agent-loader.ts", "web/lib/runner-v2/agent-bootstrap-plan.ts", "lib/chain-runner.sh"],
    samples: { root: "organization", patterns: [["agents", "*", "agent.json"]], format: "json" },
  }),
  shape({
    id: "runner-event",
    name: "Runner Event",
    category: "core",
    description: "Physical key-value handoff event normalized through the runner-v2 parser.",
    scope: "project",
    format: "key-value",
    storage: ["{runtimeRoot}/events/*.event"],
    assurance: "drift-checked",
    schemaPath: "lib/schemas/event.schema.json",
    typePaths: ["web/lib/runner-v2/events.ts"],
    validatorPaths: ["web/lib/runner-v2/events.ts", "web/app/api/validate/route.ts"],
    writers: ["lib/event-trigger.sh", "web/lib/runner-v2/adapters.ts", "lib/agent-functions.sh", "web/app/api/events/emit/route.ts", "web/app/api/chain-triggers/route.ts", "web/lib/runner-v2/probe.ts"],
    readers: ["web/lib/runner-v2/events.ts", "web/lib/runner-v2/monitor-io.ts", "lib/chain-event-watcher.sh"],
    samples: { root: "project", patterns: [["events", "*.event"]], format: "key-value" },
    notes: ["Event names are open vocabulary; the schema documents known platform events without closing chain-defined handoffs."],
  }),
  shape({
    id: "run-record",
    name: "Run Record",
    category: "core",
    description: "Durable chain execution state shared by shell writers, web APIs, and runner-v2.",
    scope: "project",
    format: "json",
    storage: ["{runtimeRoot}/runs/{runId}/run.json"],
    assurance: "drift-checked",
    schemaPath: "lib/schemas/run.schema.json",
    typePaths: ["web/lib/runner-v2/run-state.ts", "web/lib/types.ts"],
    validatorPaths: ["web/app/api/validate/route.ts"],
    writers: [
      "lib/run-lib.sh",
      "web/lib/runs/chain-run-service.ts",
      "web/lib/runner-v2/run-state.ts",
      "web/lib/runner-v2/completion-recovery.ts",
      "web/lib/runs/run-json-lock.ts",
      "web/app/api/runs/[id]/approve/route.ts",
      "web/app/api/runs/[id]/resume/route.ts",
      "web/app/api/runs/[id]/route.ts",
      "web/app/api/runs/[id]/stop/route.ts",
      "web/app/api/agents/resume/route.ts",
      "web/app/api/system/stop-all/route.ts",
      "web/app/api/mentiko-mcp/ops/context/runs/cancel/route.ts",
    ],
    readers: ["web/lib/runs/runs-store.ts", "web/lib/runs/run-reconciler.ts", "web/app/api/runs/route.ts"],
    samples: { root: "project", patterns: [["runs", "*", "run.json"]], format: "json" },
    notes: ["Current job/run stores resolve through namespace paths in several call sites; default project collapse hides that scope drift."],
  }),
  shape({
    id: "job-record",
    name: "Generation Job",
    category: "core",
    description: "Detached generation job input, lifecycle, run linkage, result, and error state.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/jobs/job-{id}.json", "{projectRoot}/jobs/job-{id}.json"],
    assurance: "typed",
    typePaths: ["web/lib/runs/job-store.ts", "web/lib/runs/job-types.ts"],
    validatorPaths: ["web/lib/generation/payload-contract.mjs"],
    writers: [
      "web/lib/runs/job-store.ts",
      "lib/job-runner.mjs",
      "web/lib/generation/generation-chain-dispatch.ts",
      "web/lib/tasks/task-outcome-audit.ts",
      "web/app/api/jobs/route.ts",
      "web/app/api/jobs/[id]/complete/route.ts",
      "web/app/api/chains/recommend/route.ts",
      "web/app/api/agents/registry/generate/route.ts",
      "web/app/api/agents/registry/edit/route.ts",
      "web/app/api/artifact-templates/generate/route.ts",
      "web/app/api/links/generate/route.ts",
      "web/app/api/links/runs/[runId]/generate-summary/route.ts",
      "web/app/api/webhooks/generate/route.ts",
      "web/app/api/events/triggers/generate/route.ts",
      "web/app/api/generation-templates/test/route.ts",
      "web/app/api/decisions/[id]/retrospective/route.ts",
      "web/app/api/decisions/[id]/guided/synthesize/route.ts",
    ],
    readers: [
      "web/lib/runs/job-store.ts",
      "web/lib/tasks/task-outcome-audit.ts",
      "lib/mentiko-mcp/handlers/jobs.ts",
      "web/app/api/jobs/route.ts",
      "web/app/api/jobs/[id]/route.ts",
      "web/app/api/jobs/[id]/status/route.ts",
      "web/app/api/jobs/[id]/complete/route.ts",
      "web/app/api/tasks/auto-run/route.ts",
      "web/app/api/decisions/[id]/route.ts",
      "web/app/api/decisions/[id]/research/route.ts",
      "web/app/api/decisions/[id]/retrospective/route.ts",
      "web/app/api/decisions/[id]/guided/questions/route.ts",
      "web/app/api/decisions/[id]/guided/options/route.ts",
      "web/app/api/decisions/[id]/guided/plan/route.ts",
      "web/app/api/decisions/[id]/guided/synthesize/route.ts",
      "web/app/api/links/generate/apply/route.ts",
      "web/app/api/mentiko-mcp/ops/jobs/[id]/route.ts",
    ],
    samples: { root: "namespace", patterns: [["jobs", "*.json"]], format: "json" },
    notes: [
      "lib/job-runner.mjs resolves JOBS_DIR from PROJECT_ROOT; web/lib/runs/job-store.ts resolves it from the namespace root. Default org/project collapse makes these the same directory, so the split only surfaces under a non-default org or project.",
      "result.output is the raw text of the run's generation-result.json, so it is a JSON-encoded string rather than prose (job-store.ts readCompletedRunResult; normalizeResultForKind re-wraps bare objects the same way). Consumers must parse it.",
      "input and result are Record<string, unknown>, so the observed sub-paths under them are unmodeled; only the job envelope is typed.",
    ],
  }),
  shape({
    id: "batch-run-record",
    name: "Batch Run Record",
    category: "core",
    description: "Multi-chain batch request, aggregate lifecycle, per-chain result, PID, and optional chain snapshot.",
    scope: "namespace",
    format: "mixed",
    storage: ["{namespaceRoot}/batches/{batchId}/batch.json", "{namespaceRoot}/batches/{batchId}/{chainId}/result.json", "{namespaceRoot}/batches/{batchId}/{chainId}/pid", "{namespaceRoot}/batches/{batchId}/{chainId}/chain.json"],
    assurance: "typed",
    typePaths: ["web/app/api/chains/run-batch/route.ts"],
    writers: ["web/app/api/chains/run-batch/route.ts", "lib/multi-chain-runner.sh"],
    readers: ["web/app/api/chains/run-batch/route.ts", "lib/multi-chain-runner.sh"],
    samples: { root: "namespace", patterns: [["batches", "*", "batch.json"], ["batches", "*", "*", "result.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "decision-record",
    name: "Decision Record",
    category: "core",
    description: "Classic or guided decision state, generated options, human selection, and execution plan.",
    scope: "project",
    format: "json",
    storage: ["{orgRoot}/decisions/{id}.json", "{orgRoot}/projects/{encodedWorkspace}/decisions/{id}.json"],
    assurance: "typed",
    typePaths: ["web/lib/decisions/decision-types.ts"],
    writers: ["web/lib/decisions/decision-storage.ts", "web/lib/decisions/decision-run-results.ts", "web/lib/decisions/decision-resolution.ts"],
    readers: ["web/lib/decisions/decision-storage.ts", "web/app/api/decisions/[id]/route.ts"],
    samples: {
      root: "organization",
      patterns: [["decisions", "*.json"], ["projects", "*", "decisions", "*.json"]],
      format: "json",
    },
  }),
  shape({
    id: "decision-phase-claim",
    name: "Decision Phase Claim",
    category: "work",
    description: "Cross-process single-flight claim and adopted run identity for automatic decision phases.",
    scope: "project",
    format: "json",
    storage: ["{runtimeRoot}/runs/.decision-phase-claims/{fingerprint}.json"],
    assurance: "typed",
    typePaths: ["web/lib/decisions/decision-auto-advance.ts"],
    writers: ["web/lib/decisions/decision-auto-advance.ts"],
    readers: ["web/lib/decisions/decision-auto-advance.ts"],
    samples: { root: "project", patterns: [["runs", ".decision-phase-claims", "*.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "task-database",
    name: "Task Database",
    category: "work",
    description: "Tasks, dependencies, comments, counters, and migration state.",
    scope: "namespace",
    format: "sqlite",
    storage: ["{namespaceRoot}/data/tasks.db"],
    assurance: "enforced",
    typePaths: ["web/lib/tasks/task-store-types.ts"],
    validatorPaths: ["web/lib/tasks/task-store.ts", "web/app/api/code/tasks-db/route.ts"],
    writers: ["web/lib/tasks/task-store.ts", "web/app/api/tasks/reconcile/route.ts"],
    readers: ["web/lib/tasks/task-store.ts", "web/app/api/code/tasks-db/route.ts"],
    samples: { root: "namespace", patterns: [["data", "tasks.db"]], format: "sqlite" },
  }),
  shape({
    id: "task-generation-payload",
    name: "Generated Task Definition",
    category: "work",
    description: "Portable task-generation payload before it is normalized into tasks.db rows.",
    scope: "run",
    format: "json",
    storage: ["{runRoot}/{runId}/artifacts/draft-child-tasks.json", "generation response payloads"],
    assurance: "enforced",
    schemaPath: "lib/schemas/task.schema.json",
    typePaths: ["web/lib/tasks/generated-task-import.ts", "web/lib/tasks/generated-task-validation.ts"],
    validatorPaths: ["web/lib/tasks/generated-task-validation.ts", "lib/job-runner.mjs"],
    writers: ["web/lib/event-artifacts/event-artifact-runner.ts", "task generation agents"],
    readers: ["lib/job-runner.mjs", "web/lib/event-artifacts/event-artifact-actions.ts", "web/lib/tasks/generated-task-import.ts"],
    samples: { root: "project", patterns: [["runs", "*", "artifacts", "draft-child-tasks.json"]], format: "json" },
  }),
  shape({
    id: "review-database",
    name: "Review Database",
    category: "work",
    description: "Peer reviews, assignments, comments, counters, and migration state.",
    scope: "namespace",
    format: "sqlite",
    storage: ["{namespaceRoot}/data/reviews.db"],
    assurance: "enforced",
    typePaths: ["web/lib/reviews/review-store-types.ts"],
    validatorPaths: ["web/lib/reviews/review-store.ts"],
    writers: ["web/lib/reviews/review-store.ts"],
    readers: ["web/lib/reviews/review-store.ts", "web/app/api/reviews/route.ts"],
    samples: { root: "namespace", patterns: [["data", "reviews.db"]], format: "sqlite" },
  }),
  shape({
    id: "runner-v2-attempt",
    name: "Runner-v2 Agent Attempt",
    category: "runner",
    description: "Typed attempt phase history, instruction ledger, process evidence, and terminal reason embedded in run.json.",
    scope: "run",
    format: "json",
    storage: ["run.json → runnerV2.attempts[]"],
    assurance: "drift-checked",
    schemaPath: "lib/schemas/run.schema.json",
    typePaths: ["web/lib/runner-v2/agent-attempt.ts"],
    writers: ["web/lib/runner-v2/agent-attempt.ts"],
    readers: ["web/lib/runner-v2/agent-attempt.ts", "web/lib/runner-v2/completion-runner.ts"],
    samples: {
      root: "project",
      patterns: [["runs", "*", "run.json"]],
      format: "json",
      valuePath: "runnerV2.attempts",
      schemaPointer: "/definitions/agentAttempt",
    },
  }),
  shape({
    id: "runner-v2-pending-handoff",
    name: "Runner-v2 Pending Handoff",
    category: "runner",
    description: "Detached routed-launch process and exact downstream agent targets embedded in run.json.",
    scope: "run",
    format: "json",
    storage: ["run.json → runnerV2.pendingHandoffs[]"],
    assurance: "drift-checked",
    schemaPath: "lib/schemas/run.schema.json",
    typePaths: ["web/lib/runner-v2/handoff-liveness.ts"],
    writers: ["web/lib/runner-v2/adapters.ts", "web/lib/runner-v2/run-state.ts"],
    readers: ["web/lib/runner-v2/handoff-liveness.ts", "web/lib/runs/run-reconciler.ts"],
    samples: {
      root: "project",
      patterns: [["runs", "*", "run.json"]],
      format: "json",
      valuePath: "runnerV2.pendingHandoffs",
      schemaPointer: "/definitions/pendingHandoff",
    },
  }),
  shape({
    id: "runner-agent-state",
    name: "Runner Agent State",
    category: "runner",
    description: "Legacy line-oriented per-agent execution status overlaid on run.json while an agent is running.",
    scope: "project",
    format: "key-value",
    storage: ["{runtimeRoot}/state/{session}.state", "{runRoot}/{runId}/state/{session}.state"],
    assurance: "observed",
    writers: ["lib/chain-runner.sh", "web/lib/runner-v2/bootstrap-executor.ts"],
    readers: ["web/lib/runs/run-state.ts", "lib/chain-runner-complete.sh"],
    samples: { root: "project", patterns: [["state", "*.state"], ["runs", "*", "state", "*.state"]], format: "key-value" },
  }),
  shape({
    id: "chain-loop-state",
    name: "Chain Loop State",
    category: "runner",
    description: "Loop counter, visited transitions, and current agent for loop-guarded chains.",
    scope: "run",
    format: "mixed",
    storage: ["{runRoot}/{runId}/chain-loop-state.json", "{runRoot}/{runId}/chain_loop_tracker.txt"],
    assurance: "typed",
    typePaths: ["web/lib/runner-v2/loop-state.ts"],
    writers: ["web/lib/runner-v2/loop-state.ts", "lib/chain-runner-complete.sh"],
    readers: ["web/lib/runner-v2/loop-state.ts", "web/lib/runner-v2/routing.ts", "lib/chain-runner-complete.sh"],
    samples: { root: "project", patterns: [["runs", "*", "chain-loop-state.json"]], format: "json" },
  }),
  shape({
    id: "external-effects-ledger",
    name: "External Effects Ledger",
    category: "runner",
    description: "Idempotent queued/dispatched/skipped/failed side effects for webhooks, tasks, notifications, plugins, and hooks.",
    scope: "run",
    format: "jsonl",
    storage: ["{runRoot}/{runId}/state/external-effects.dispatch.jsonl", "{runtimeRoot}/state/external-effects.dispatch.jsonl"],
    assurance: "typed",
    typePaths: ["web/lib/runner-v2/external-effects.ts"],
    writers: ["web/lib/runner-v2/external-effects.ts"],
    readers: ["web/lib/runner-v2/external-effects.ts", "web/lib/runner-v2/adapters.ts"],
    samples: { root: "project", patterns: [["state", "external-effects.dispatch.jsonl"], ["runs", "*", "state", "external-effects.dispatch.jsonl"]], format: "jsonl" },
  }),
  shape({
    id: "generation-import-ledger",
    name: "Generation Import Ledger",
    category: "runner",
    description: "Append-only generation import command outcome and captured process evidence.",
    scope: "run",
    format: "jsonl",
    storage: ["{runRoot}/{runId}/state/generation-import.jsonl", "{runtimeRoot}/state/generation-import.jsonl"],
    assurance: "typed",
    typePaths: ["web/lib/runner-v2/executor.ts"],
    writers: ["web/lib/runner-v2/adapters.ts"],
    readers: ["web/lib/runner-v2/completion-entrypoint.ts"],
    samples: { root: "project", patterns: [["state", "generation-import.jsonl"], ["runs", "*", "state", "generation-import.jsonl"]], format: "jsonl" },
  }),
  shape({
    id: "event-artifact-ledger",
    name: "Event Artifact Execution Ledger",
    category: "runner",
    description: "Append-only event-to-artifact execution, dedupe, review, apply, and retry lifecycle.",
    scope: "run",
    format: "jsonl",
    storage: ["{runRoot}/{runId}/artifacts/event-artifact-executions.jsonl"],
    assurance: "typed",
    typePaths: ["web/lib/event-artifacts/event-artifact-ledger.ts"],
    writers: ["web/lib/event-artifacts/event-artifact-ledger.ts"],
    readers: ["web/lib/event-artifacts/event-artifact-ledger.ts", "web/app/api/runs/[id]/event-artifacts/route.ts"],
    samples: { root: "project", patterns: [["runs", "*", "artifacts", "event-artifact-executions.jsonl"]], format: "jsonl" },
  }),
  shape({
    id: "runspace-manifest",
    name: "Runspace Manifest",
    category: "runner",
    description: "Per-run shared artifact manifest initialized by the shell runner.",
    scope: "run",
    format: "json",
    storage: ["{runRoot}/{runId}/runspace/manifest.json"],
    assurance: "observed",
    writers: ["lib/chain-runner.sh"],
    readers: ["lib/chain-runner.sh", "agents and operator tooling"],
    samples: { root: "project", patterns: [["runs", "*", "runspace", "manifest.json"]], format: "json" },
    notes: ["The initialized contract has run_id, chain, and artifacts; artifact entries remain open vocabulary."],
  }),
  shape({
    id: "session-policy-ledger",
    name: "Session Policy Ledger",
    category: "runner",
    description: "Append-only decisions about session reuse, isolation, and launch policy.",
    scope: "project",
    format: "jsonl",
    storage: ["{runtimeRoot}/state/session-policy.jsonl", "{runRoot}/{runId}/state/session-policy.jsonl"],
    assurance: "typed",
    typePaths: ["web/lib/runner-v2/adapters.ts"],
    writers: ["web/lib/runner-v2/adapters.ts"],
    readers: ["web/lib/runner-v2/adapters.ts"],
    samples: { root: "project", patterns: [["state", "session-policy.jsonl"], ["runs", "*", "state", "session-policy.jsonl"]], format: "jsonl" },
  }),
  shape({
    id: "watchdog-hook-dispatch",
    name: "Watchdog Hook Dispatch Ledger",
    category: "runner",
    description: "Append-only record of runner-v2 terminal or error hooks and their dispatch count.",
    scope: "run",
    format: "jsonl",
    storage: ["{runRoot}/{runId}/state/watchdog-hooks/dispatch.jsonl", "{runtimeRoot}/state/watchdog-hooks/dispatch.jsonl"],
    assurance: "typed",
    typePaths: ["web/lib/runner-v2/adapters.ts"],
    writers: ["web/lib/runner-v2/adapters.ts"],
    readers: ["web/lib/runner-v2/adapters.ts", "operator runtime diagnostics"],
    samples: {
      root: "project",
      patterns: [["runs", "*", "state", "watchdog-hooks", "dispatch.jsonl"], ["state", "watchdog-hooks", "dispatch.jsonl"]],
      format: "jsonl",
    },
    sensitive: true,
  }),
  shape({
    id: "fan-group-state",
    name: "Fan Group State",
    category: "runner",
    description: "Fan-out member completion and fan-in readiness, with a legacy text fallback.",
    scope: "project",
    format: "mixed",
    storage: ["{runtimeRoot}/state/fan-groups/{groupId}.json", "{runtimeRoot}/state/fan-groups/{groupId}.state"],
    assurance: "typed",
    typePaths: ["web/lib/runner-v2/fan-group.ts", "web/lib/runner-v2/fan-group-store.ts"],
    writers: ["web/lib/runner-v2/fan-group-store.ts", "lib/routing-lib.sh", "lib/chain-runner-complete.sh"],
    readers: ["web/lib/runner-v2/fan-group-store.ts", "web/lib/runner-v2/completion-runner.ts", "lib/routing-lib.sh", "lib/chain-runner-complete.sh"],
    samples: { root: "project", patterns: [["state", "fan-groups", "*.json"]], format: "json" },
  }),
  shape({
    id: "run-artifacts",
    name: "Run Artifacts",
    category: "runner",
    description: "Typed handoff artifacts and arbitrary agent-created outputs sharing the run artifact directory.",
    scope: "run",
    format: "mixed",
    storage: ["{runRoot}/{runId}/artifacts/*"],
    assurance: "open",
    writers: ["agents", "web/app/api/jobs/[id]/complete/route.ts", "web/lib/runner-v2/adapters.ts"],
    readers: ["web/lib/runs/job-store.ts", "web/lib/tasks/run-outcome-evidence.ts", "web/lib/event-artifacts/event-artifact-ledger.ts"],
    samples: { root: "project", patterns: [["runs", "*", "artifacts", "*.json"]], format: "json" },
    notes: ["Known JSON handoffs coexist with arbitrary code and prose. The catalog observes JSON shapes but does not imply a closed artifact contract."],
  }),
  shape({
    id: "workspace-registry",
    name: "Workspace Registry",
    category: "configuration",
    description: "Local, SSH, and Docker execution targets plus project, model, access, and auto-run settings.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/workspaces.json"],
    assurance: "typed",
    typePaths: ["web/lib/workspaces/workspace-storage.ts"],
    writers: ["web/lib/workspaces/workspace-storage.ts", "web/app/api/workspaces/route.ts"],
    readers: ["web/lib/workspaces/workspace-storage.ts", "web/lib/runner-v2/agent-bootstrap-plan.ts"],
    samples: { root: "organization", patterns: [["workspaces.json"]], format: "json" },
  }),
  shape({
    id: "workspace-ssh-key",
    name: "Workspace SSH Key",
    category: "configuration",
    description: "Namespace SSH private key plus public metadata used by remote workspaces.",
    scope: "namespace",
    format: "mixed",
    storage: ["{namespaceRoot}/ssh-keys/{keyId}.json", "{namespaceRoot}/ssh-keys/{keyId}.key"],
    assurance: "typed",
    typePaths: ["web/app/api/workspaces/ssh-keys/route.ts"],
    writers: ["web/app/api/workspaces/ssh-keys/route.ts"],
    readers: ["web/app/api/workspaces/ssh-keys/route.ts"],
    samples: { root: "namespace", patterns: [["ssh-keys", "*.json"]], format: "json" },
    sensitive: true,
    notes: ["The catalog inspects metadata only. Private .key contents are never opened."],
  }),
  shape({
    id: "config-profile",
    name: "Legacy Execution Config Profile",
    category: "configuration",
    description: "Operator-managed shell-runner execution and model overlays. No active web producer exists.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/config-profiles/{execution|model}/{name}.json"],
    assurance: "open",
    typePaths: ["lib/chain-runner.sh"],
    writers: ["operators and deployment tooling"],
    readers: ["lib/chain-runner.sh", "lib/config.sh"],
    samples: { root: "organization", patterns: [["config-profiles", "*", "*.json"]], format: "json" },
    notes: ["The directory is created by config.sh, but this checkout has no current web writer or canonical validator."],
  }),
  shape({
    id: "agent-profile",
    name: "Agent Profile",
    category: "configuration",
    description: "CLI command, model, environment, transcript root, readiness, and default selection.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/agent-profiles/{profileId}.json"],
    assurance: "enforced",
    typePaths: ["web/lib/types.ts", "web/lib/agents/agent-profile-storage.ts"],
    validatorPaths: ["web/lib/agents/agent-profile-storage.ts"],
    writers: ["web/lib/agents/agent-profile-storage.ts"],
    readers: ["web/lib/agents/agent-profile-storage.ts", "lib/agent-profile.sh", "web/lib/runner-v2/monitor-live-io.ts"],
    samples: { root: "organization", patterns: [["agent-profiles", "*.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "plugin-registry",
    name: "Plugin Registry",
    category: "configuration",
    description: "Enabled plugin registrations, manifests, and encrypted plugin configuration.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/plugins/registry.json"],
    assurance: "typed",
    typePaths: ["web/lib/system/plugin-types.ts", "web/lib/system/plugin-registry.ts"],
    writers: ["web/lib/system/plugin-registry.ts"],
    readers: ["web/lib/system/plugin-registry.ts", "lib/plugin-runner.sh"],
    samples: { root: "organization", patterns: [["plugins", "registry.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "shared-resources",
    name: "Organization Shared Resources",
    category: "configuration",
    description: "Organization-shared chain snapshots, configuration profiles, and encrypted secrets.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/shared/chains/*.json", "{orgRoot}/shared/profiles/{type}/*.json", "{orgRoot}/shared/secrets/*.json"],
    assurance: "typed",
    typePaths: ["web/lib/system/shared-resources.ts"],
    writers: ["web/lib/system/shared-resources.ts"],
    readers: ["web/lib/system/shared-resources.ts"],
    samples: {
      root: "organization",
      patterns: [["shared", "chains", "*.json"], ["shared", "profiles", "*", "*.json"], ["shared", "secrets", "*.json"]],
      format: "json",
    },
    sensitive: true,
    notes: ["Shared chain/profile wrappers contain nested user-defined data; shared secret values are encrypted at rest."],
  }),
  shape({
    id: "marketplace-ratings",
    name: "Marketplace Ratings",
    category: "configuration",
    description: "Per-template and per-agent rating aggregates, distributions, and use counts.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/ratings.json"],
    assurance: "typed",
    typePaths: ["web/lib/system/templates.ts"],
    writers: ["web/app/api/templates/[id]/rate/route.ts", "web/app/api/templates/[id]/use/route.ts", "web/app/api/agents/marketplace/[id]/rate/route.ts"],
    readers: ["web/lib/system/templates.ts", "web/app/api/agents/marketplace/route.ts"],
    samples: { root: "namespace", patterns: [["ratings.json"]], format: "json" },
  }),
  shape({
    id: "schedule",
    name: "Schedule",
    category: "configuration",
    description: "Cron/file trigger, timezone, workspace target, task binding, and chain launch configuration.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/schedules.json", "{orgRoot}/schedules/{id}/.snooze"],
    assurance: "enforced",
    schemaPath: "lib/schemas/schedule.schema.json",
    typePaths: ["web/lib/types.ts", "web/lib/schedules/schedule-storage.ts"],
    validatorPaths: ["web/lib/schedules/schedule-utils.ts", "web/lib/schedules/schedule-targets.ts"],
    writers: ["web/lib/schedules/schedule-storage.ts", "web/app/api/schedules/route.ts", "web/app/api/schedules/snooze/route.ts"],
    readers: ["web/lib/schedules/schedule-storage.ts", "web/lib/schedules/scheduler-service.ts", "web/app/api/schedules/snooze/route.ts"],
    samples: { root: "organization", patterns: [["schedules.json"]], format: "json" },
  }),
  shape({
    id: "schedule-runtime-state",
    name: "Schedule Runtime State",
    category: "configuration",
    description: "Last-run timestamps and file-trigger fingerprints used by typed and shell scheduling paths.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/schedules/state.json", "{orgRoot}/schedules/file-trigger-state.json"],
    assurance: "typed",
    typePaths: ["web/lib/schedules/scheduler-service.ts", "web/lib/runner-v2/adapters.ts"],
    writers: ["web/lib/schedules/scheduler-service.ts", "web/lib/runner-v2/adapters.ts"],
    readers: ["web/lib/schedules/scheduler-service.ts"],
    samples: { root: "organization", patterns: [["schedules", "state.json"], ["schedules", "file-trigger-state.json"]], format: "json" },
    notes: ["Runner adapters can resolve schedules through project runtime state while the scheduler uses organization paths."],
  }),
  shape({
    id: "schedule-execution-history",
    name: "Schedule Execution History",
    category: "configuration",
    description: "Bounded per-chain execution starts, terminal outcomes, outputs, errors, and retry metadata.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/schedules/history/{chainId}.json"],
    assurance: "enforced",
    typePaths: ["web/lib/schedules/schedule-utils.ts"],
    validatorPaths: ["web/lib/schedules/schedule-utils.ts"],
    writers: ["web/app/api/schedules/history/route.ts"],
    readers: ["web/app/api/schedules/history/route.ts"],
    samples: { root: "organization", patterns: [["schedules", "history", "*.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "scheduled-application",
    name: "Scheduled Application",
    category: "configuration",
    description: "Durable scheduled action/application registry.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/applications.json"],
    assurance: "typed",
    typePaths: ["web/lib/schedules/scheduled-application-storage.ts"],
    writers: ["web/lib/schedules/scheduled-application-storage.ts"],
    readers: ["web/lib/schedules/scheduled-application-storage.ts"],
    samples: { root: "organization", patterns: [["applications.json"]], format: "json" },
  }),
  shape({
    id: "generation-templates",
    name: "Generation Templates",
    category: "configuration",
    description: "Prompt templates for chain, task, decision, link, and artifact generation.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/generation-templates.json"],
    assurance: "typed",
    typePaths: ["web/lib/generation/generation-template-storage.ts"],
    writers: ["web/lib/generation/generation-template-storage.ts"],
    readers: ["web/lib/generation/generation-template-storage.ts", "web/app/api/generation-templates/route.ts"],
    samples: { root: "organization", patterns: [["generation-templates.json"]], format: "json" },
  }),
  shape({
    id: "chain-template",
    name: "Chain Template",
    category: "configuration",
    description: "User-created template metadata with an embedded chain plus a compatibility chain snapshot.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/templates/{slug}/template.json", "{orgRoot}/templates/{slug}/chain.json"],
    assurance: "typed",
    typePaths: ["web/app/api/templates/route.ts", "web/lib/system/templates.ts"],
    writers: ["web/app/api/templates/route.ts", "web/app/api/mentiko-mcp/ops/templates/route.ts"],
    readers: ["web/app/api/templates/route.ts", "web/lib/system/templates.ts"],
    samples: { root: "organization", patterns: [["templates", "*", "template.json"]], format: "json" },
  }),
  shape({
    id: "artifact-templates",
    name: "Artifact Templates",
    category: "configuration",
    description: "Reusable artifact format, content, and metadata templates.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/artifact-templates.json"],
    assurance: "typed",
    typePaths: ["web/lib/system/artifact-template-storage.ts"],
    writers: ["web/lib/system/artifact-template-storage.ts"],
    readers: ["web/lib/system/artifact-template-storage.ts"],
    samples: { root: "organization", patterns: [["artifact-templates.json"]], format: "json" },
  }),
  shape({
    id: "notifications",
    name: "Notifications",
    category: "configuration",
    description: "User-visible notification records and related run/chain/task metadata.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/notifications/notifications.json"],
    assurance: "typed",
    typePaths: ["web/lib/notifications/notification-server.ts", "web/lib/notifications/notifications-store.ts"],
    writers: ["web/lib/notifications/notification-server.ts", "web/app/api/notifications/route.ts", "web/app/api/notifications/[id]/route.ts"],
    readers: ["web/lib/notifications/notification-server.ts", "web/app/api/notifications/route.ts", "web/app/api/notifications/[id]/route.ts"],
    samples: { root: "namespace", patterns: [["notifications", "notifications.json"]], format: "json" },
  }),
  shape({
    id: "notification-preferences",
    name: "Notification Preferences",
    category: "configuration",
    description: "Per-user channels, categories, quiet hours, delivery endpoints, and budget threshold.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/notifications/{userId}.json"],
    assurance: "typed",
    typePaths: ["web/lib/notifications/notification-prefs.ts"],
    writers: ["web/lib/notifications/notification-prefs.ts", "web/app/api/notifications/preferences/route.ts"],
    readers: ["web/lib/notifications/notification-prefs.ts", "web/app/api/notifications/dispatch/route.ts"],
    samples: {
      root: "organization",
      patterns: [["notifications", "*.json"]],
      excludePatterns: [["notifications", "notifications.json"]],
      format: "json",
    },
    sensitive: true,
  }),
  shape({
    id: "notification-delivery-settings",
    name: "Notification Delivery Settings",
    category: "configuration",
    description: "Namespace-wide category/channel matrix, quiet hours, endpoints, sound, and desktop settings.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/settings/notifications.json"],
    assurance: "typed",
    typePaths: ["web/app/api/settings/notifications/route.ts"],
    writers: ["web/app/api/settings/notifications/route.ts"],
    readers: ["web/app/api/settings/notifications/route.ts"],
    samples: { root: "namespace", patterns: [["settings", "notifications.json"]], format: "json" },
    sensitive: true,
    notes: ["This older namespace-wide contract is separate from per-user organization notification preferences."],
  }),
  shape({
    id: "integration-settings",
    name: "Integration Settings",
    category: "configuration",
    description: "Enabled GitHub, Slack, Teams, and email integrations with non-secret addressing metadata.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/integrations/config.json"],
    assurance: "typed",
    typePaths: ["web/app/api/integrations/save/route.ts"],
    writers: ["web/app/api/integrations/save/route.ts"],
    readers: ["integration settings UI and operator tooling"],
    samples: { root: "namespace", patterns: [["integrations", "config.json"]], format: "json" },
    sensitive: true,
    notes: ["Tokens and webhook URLs are intentionally excluded by the writer and resolved from environment configuration."],
  }),
  shape({
    id: "secret-record",
    name: "Encrypted Secret Record",
    category: "configuration",
    description: "Secret metadata plus encrypted value. Catalog evidence exposes keys and types only, never values.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/secrets/{secretId}.json"],
    assurance: "typed",
    typePaths: ["web/lib/secrets/secrets-store.ts"],
    validatorPaths: ["web/lib/secrets/secrets-store.ts"],
    writers: ["web/lib/secrets/secrets-store.ts"],
    readers: ["web/lib/secrets/secrets-store.ts", "bin/secrets-resolve.mjs"],
    samples: { root: "organization", patterns: [["secrets", "*.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "link-record",
    name: "Agent Link",
    category: "work",
    description: "Two-agent debate, collaboration, or review link and its live run state.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/links/{linkId}/link.json", "{runtimeRoot}/runs/{runId}/run.json (link run)"],
    assurance: "typed",
    typePaths: ["web/lib/links/link-types.ts"],
    writers: [
      "web/lib/links/link-utils.ts",
      "web/app/api/links/save/route.ts",
      "web/app/api/links/run/route.ts",
      "web/app/api/links/generate/apply/route.ts",
      "web/app/api/links/runs/[runId]/escalate/route.ts",
      "web/app/api/links/runs/[runId]/reply/route.ts",
      "web/app/api/links/runs/[runId]/stop/route.ts",
    ],
    readers: ["web/lib/links/link-utils.ts", "web/app/api/links/[id]/route.ts"],
    samples: { root: "organization", patterns: [["links", "*", "link.json"]], format: "json" },
  }),
  shape({
    id: "peer-escalation",
    name: "Peer Escalation",
    category: "work",
    description: "Peer-session registry, escalation history, point-in-time snapshots, and pending human reply handoff.",
    scope: "namespace",
    format: "mixed",
    storage: ["{namespaceRoot}/peer-escalations/registry.json", "{namespaceRoot}/peer-escalations/{sessionId}/history.json", "{namespaceRoot}/peer-escalations/{sessionId}/escalation-{n}.json", "{namespaceRoot}/peer-escalations/{sessionId}/reply.txt"],
    assurance: "typed",
    typePaths: ["web/lib/system/peer-escalations.ts"],
    writers: ["web/lib/system/peer-escalations.ts", "web/app/api/telegram/webhook/route.ts"],
    readers: ["web/lib/system/peer-escalations.ts", "web/app/api/telegram/webhook/route.ts"],
    samples: {
      root: "namespace",
      patterns: [["peer-escalations", "registry.json"], ["peer-escalations", "*", "history.json"], ["peer-escalations", "*", "escalation-*.json"]],
      format: "json",
    },
    sensitive: true,
    notes: ["Free-text reply.txt is intentionally not read by the catalog scanner."],
  }),
  shape({
    id: "approval-request",
    name: "Approval Request",
    category: "work",
    description: "Human approval policy and request lifecycle records.",
    scope: "organization",
    format: "mixed",
    storage: ["{orgRoot}/approvals/{chainId}-config.json", "{orgRoot}/approvals/requests.jsonl", "{orgRoot}/approvals/{requestId}.json"],
    assurance: "typed",
    typePaths: ["web/lib/system/approval-types.ts", "web/lib/system/approval-storage.ts"],
    writers: ["web/lib/system/approval-storage.ts"],
    readers: ["web/lib/system/approval-storage.ts", "web/app/api/approvals/route.ts"],
    samples: { root: "organization", patterns: [["approvals", "*.json"]], format: "json" },
  }),
  shape({
    id: "webhook-subscriptions",
    name: "Webhook Subscription",
    category: "integrations",
    description: "Legacy/API-facing webhook subscription with encrypted signing secret and event filters.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/webhooks/subscriptions.json"],
    assurance: "typed",
    typePaths: ["web/lib/webhooks/webhook-types.ts"],
    validatorPaths: ["web/lib/webhooks/webhook-storage.ts"],
    writers: ["web/lib/webhooks/webhook-storage.ts", "web/app/api/webhooks/route.ts"],
    readers: ["web/lib/webhooks/webhook-storage.ts", "web/app/api/webhooks/[id]/receive/route.ts"],
    samples: { root: "organization", patterns: [["webhooks", "subscriptions.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "webhook-event-log",
    name: "Webhook Event Log",
    category: "integrations",
    description: "Append-only receipt, dispatch, test, and deletion events for webhook subscriptions.",
    scope: "organization",
    format: "jsonl",
    storage: ["{orgRoot}/webhooks/events.jsonl"],
    assurance: "typed",
    typePaths: ["web/lib/webhooks/webhook-types.ts"],
    writers: ["web/lib/webhooks/webhook-storage.ts"],
    readers: ["web/lib/webhooks/webhook-storage.ts", "web/app/api/webhooks/logs/route.ts"],
    samples: { root: "organization", patterns: [["webhooks", "events.jsonl"]], format: "jsonl" },
  }),
  shape({
    id: "inbound-webhooks",
    name: "Inbound Webhook Config",
    category: "integrations",
    description: "Token-hashed HTTP trigger, run defaults, override policy, and usage metadata.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/inbound-webhooks.json"],
    assurance: "typed",
    typePaths: ["web/lib/webhooks/inbound-webhook-storage.ts"],
    validatorPaths: ["web/lib/webhooks/inbound-webhook-storage.ts"],
    writers: ["web/lib/webhooks/inbound-webhook-storage.ts"],
    readers: ["web/lib/webhooks/inbound-webhook-storage.ts", "web/app/api/webhooks/inbound/[token]/route.ts"],
    samples: { root: "organization", patterns: [["inbound-webhooks.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "inbound-webhook-triggers",
    name: "Inbound Webhook Trigger",
    category: "integrations",
    description: "Append-only accepted/started/failed webhook execution record.",
    scope: "organization",
    format: "jsonl",
    storage: ["{orgRoot}/inbound-webhook-triggers.jsonl"],
    assurance: "typed",
    typePaths: ["web/lib/webhooks/inbound-webhook-storage.ts"],
    writers: ["web/lib/webhooks/inbound-webhook-storage.ts"],
    readers: ["web/lib/webhooks/inbound-webhook-storage.ts"],
    samples: { root: "organization", patterns: [["inbound-webhook-triggers.jsonl"]], format: "jsonl" },
  }),
  shape({
    id: "inbound-webhook-idempotency",
    name: "Inbound Webhook Idempotency",
    category: "integrations",
    description: "Append-only completed dedupe records plus atomic in-flight claim files.",
    scope: "organization",
    format: "mixed",
    storage: ["{orgRoot}/inbound-webhook-idempotency.jsonl", "{orgRoot}/inbound-webhook-idempotency-claims/{hash}.json"],
    assurance: "typed",
    typePaths: ["web/lib/webhooks/inbound-webhook-storage.ts"],
    writers: ["web/lib/webhooks/inbound-webhook-storage.ts"],
    readers: ["web/lib/webhooks/inbound-webhook-storage.ts", "web/app/api/webhooks/inbound/[token]/route.ts"],
    samples: { root: "organization", patterns: [["inbound-webhook-idempotency.jsonl"]], format: "jsonl" },
    sensitive: true,
  }),
  shape({
    id: "outbound-webhooks",
    name: "Outbound Webhook Config",
    category: "integrations",
    description: "Signed event subscription, scope, destination, secret, and delivery policy.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/mentiko-webhooks.json"],
    assurance: "typed",
    typePaths: ["web/lib/webhooks/outbound-webhook-storage.ts"],
    validatorPaths: ["web/lib/webhooks/outbound-webhook-storage.ts"],
    writers: ["web/lib/webhooks/outbound-webhook-storage.ts"],
    readers: ["web/lib/webhooks/outbound-webhook-storage.ts", "web/lib/webhooks/webhook-utils.ts"],
    samples: { root: "organization", patterns: [["mentiko-webhooks.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "outbound-webhook-deliveries",
    name: "Outbound Webhook Delivery",
    category: "integrations",
    description: "Append-only delivered/failed/pending webhook attempt record.",
    scope: "organization",
    format: "jsonl",
    storage: ["{orgRoot}/mentiko-webhook-deliveries.jsonl"],
    assurance: "typed",
    typePaths: ["web/lib/webhooks/outbound-webhook-storage.ts"],
    writers: ["web/lib/webhooks/outbound-webhook-storage.ts"],
    readers: ["web/lib/webhooks/outbound-webhook-storage.ts"],
    samples: { root: "organization", patterns: [["mentiko-webhook-deliveries.jsonl"]], format: "jsonl" },
  }),
  shape({
    id: "email-inboxes",
    name: "Email Inbox Config",
    category: "integrations",
    description: "Inbound address, source, authentication, routing, and processing configuration.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/emails/config/inboxes.json"],
    assurance: "typed",
    typePaths: ["web/lib/email/email-types.ts"],
    writers: ["web/lib/email/email-storage.ts"],
    readers: ["web/lib/email/email-storage.ts", "web/app/api/email/inboxes/route.ts"],
    samples: { root: "organization", patterns: [["emails", "config", "inboxes.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "email-message",
    name: "Normalized Email",
    category: "integrations",
    description: "Normalized inbound message, attachment scan state, headers, and processing lifecycle.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/emails/{inbox}/{unread|processing|processed|failed}/{messageId}.json"],
    assurance: "typed",
    typePaths: ["web/lib/email/email-types.ts"],
    writers: ["web/lib/email/email-storage.ts", "web/app/api/email/inbound/route.ts"],
    readers: ["web/lib/email/email-storage.ts", "web/app/api/email/inboxes/[id]/messages/route.ts"],
    samples: { root: "organization", patterns: [["emails", "*", "*", "*.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "outbound-email",
    name: "Outbound Email Queue Entry",
    category: "integrations",
    description: "Pending/sending/sent/failed outbound message and retry state.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/emails/outbound-queue/{id}.json", "{orgRoot}/emails/outbound-{sent|failed}/{id}.json"],
    assurance: "typed",
    typePaths: ["web/lib/email/email-types.ts"],
    writers: ["web/lib/email/email-storage.ts", "web/app/api/email/send/route.ts"],
    readers: ["web/lib/email/email-storage.ts"],
    samples: { root: "organization", patterns: [["emails", "outbound-queue", "*.json"], ["emails", "outbound-sent", "*.json"], ["emails", "outbound-failed", "*.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "email-org-databases",
    name: "Organization Email Databases",
    category: "integrations",
    description: "Suppression, bounce, reputation, and outbound-sent SQLite records.",
    scope: "organization",
    format: "sqlite",
    storage: ["{orgRoot}/emails/email-suppressions.db", "{orgRoot}/emails/config/reputation.db"],
    assurance: "enforced",
    validatorPaths: ["web/lib/email/email-suppression.ts", "web/lib/email/email-reputation.ts", "web/lib/email/email-bounce.ts"],
    writers: ["web/lib/email/email-suppression.ts", "web/lib/email/email-reputation.ts", "web/lib/email/email-bounce.ts"],
    readers: ["web/lib/email/email-suppression.ts", "web/lib/email/email-reputation.ts", "web/lib/email/email-bounce.ts"],
    samples: { root: "organization", patterns: [["emails", "email-suppressions.db"], ["emails", "config", "reputation.db"]], format: "sqlite" },
    sensitive: true,
    notes: ["Bounce dedupe is a separate namespace-scoped database and is cataloged independently."],
  }),
  shape({
    id: "email-bounce-database",
    name: "Email Bounce Database",
    category: "integrations",
    description: "Namespace-wide bounce dedupe hashes and processed timestamps.",
    scope: "namespace",
    format: "sqlite",
    storage: ["{namespaceRoot}/emails/config/email-bounces.db"],
    assurance: "enforced",
    validatorPaths: ["web/lib/email/email-bounce.ts"],
    writers: ["web/lib/email/email-bounce.ts"],
    readers: ["web/lib/email/email-bounce.ts"],
    samples: { root: "namespace", patterns: [["emails", "config", "email-bounces.db"]], format: "sqlite" },
    sensitive: true,
    notes: ["This namespace-wide scope differs from organization-scoped suppression and reputation stores."],
  }),
  shape({
    id: "email-operational-metadata",
    name: "Email Operational Metadata",
    category: "integrations",
    description: "Append-only email audit events and the current daily send quota counter.",
    scope: "organization",
    format: "mixed",
    storage: ["{orgRoot}/emails/config/audit.jsonl", "{orgRoot}/emails/config/send-count.json"],
    assurance: "typed",
    typePaths: ["web/lib/email/email-types.ts", "web/lib/email/email-storage.ts"],
    writers: ["web/lib/email/email-storage.ts"],
    readers: ["web/lib/email/email-storage.ts", "web/lib/email/email-reputation.ts"],
    samples: { root: "organization", patterns: [["emails", "config", "audit.jsonl"]], format: "jsonl" },
    sensitive: true,
  }),
  shape({
    id: "organization-record",
    name: "Organization Record",
    category: "organization",
    description: "Organization identity, settings, and lifecycle record.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/org.json", "{namespaceRoot}/orgs/{orgId}.json"],
    assurance: "enforced",
    typePaths: ["web/lib/orgs/org-types.ts"],
    validatorPaths: ["web/lib/orgs/org-types.ts"],
    writers: ["web/lib/orgs/org-storage.ts"],
    readers: ["web/lib/orgs/org-storage.ts"],
    samples: { root: "namespace", patterns: [["org.json"], ["orgs", "*.json"]], format: "json" },
  }),
  shape({
    id: "organization-membership",
    name: "Organization Members and Invites",
    category: "organization",
    description: "Role-bearing members and pending/accepted/expired invitation records.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/org/members.json", "{namespaceRoot}/org/invites.json"],
    assurance: "enforced",
    typePaths: ["web/lib/orgs/org-types.ts"],
    validatorPaths: ["web/lib/orgs/org-types.ts"],
    writers: ["web/lib/orgs/org-storage.ts"],
    readers: ["web/lib/orgs/org-storage.ts"],
    samples: { root: "namespace", patterns: [["org", "members.json"], ["org", "invites.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "gdpr-pre-delete-export",
    name: "GDPR Pre-delete Export",
    category: "organization",
    description: "Restricted point-in-time user, session, account, and membership export written before account deletion.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/gdpr-exports/{userId}-{timestamp}.json"],
    assurance: "typed",
    typePaths: ["web/app/api/gdpr/delete/route.ts"],
    writers: ["web/app/api/gdpr/delete/route.ts"],
    readers: ["privacy operations and manual recovery tooling"],
    samples: { root: "organization", patterns: [["gdpr-exports", "*.json"]], format: "json" },
    sensitive: true,
    notes: ["Files are mode 0600. The catalog returns field names and types only."],
  }),
  shape({
    id: "auth-database",
    name: "Authentication Database",
    category: "organization",
    description: "Better Auth users, sessions, accounts, organizations, members, invitations, verification, and on-demand auth adjunct tables.",
    scope: "global",
    format: "sqlite",
    storage: ["{globalRoot}/data/auth.db", "{globalRoot}/data/auth.db.plain-backup (one-shot SQLCipher migration backup)"],
    assurance: "enforced",
    validatorPaths: ["web/lib/auth/auth-server.ts", "web/lib/auth/mcp-device-auth.ts", "web/lib/api/refresh-rate-limiter.ts"],
    writers: ["web/lib/auth/auth-server.ts", "web/lib/auth/mcp-device-auth.ts", "web/lib/api/refresh-rate-limiter.ts", "web/app/api/gdpr/delete/route.ts", "web/lib/system/sqlcipher-migrate.ts"],
    readers: ["web/lib/auth/auth-server.ts", "web/lib/auth/mcp-device-auth.ts"],
    samples: { root: "global", patterns: [["data", "auth.db"]], format: "sqlite" },
    sensitive: true,
    notes: ["SQLCipher migration intentionally retains a plain backup for manual verification and later operator removal; the catalog never inspects that backup."],
  }),
  shape({
    id: "chain-publish-metadata",
    name: "Published Chain Metadata",
    category: "organization",
    description: "Locally published marketplace chain snapshot and publish metadata.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/marketplace/published/{slug}/chain.json", "{namespaceRoot}/marketplace/published/{slug}/publish.json"],
    assurance: "typed",
    typePaths: ["web/lib/chains/chain-publish-store.ts"],
    writers: ["web/lib/chains/chain-publish-store.ts"],
    readers: ["web/lib/chains/chain-publish-store.ts"],
    samples: { root: "namespace", patterns: [["marketplace", "published", "*", "publish.json"]], format: "json" },
  }),
  shape({
    id: "chain-version-snapshot",
    name: "Chain Version Snapshot",
    category: "organization",
    description: "Immutable chain-save snapshots used by version history, diff, and restore routes.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/agents/versions/{chainId}/{version}.json"],
    assurance: "typed",
    typePaths: ["web/app/api/chains/save/route.ts"],
    writers: ["web/app/api/chains/save/route.ts"],
    readers: ["web/app/api/chains/[id]/versions/route.ts", "web/app/api/chains/[id]/versions/[version]/route.ts"],
    samples: { root: "organization", patterns: [["agents", "versions", "*", "*.json"]], format: "json" },
  }),
  shape({
    id: "audit-index",
    name: "Audit Index",
    category: "system",
    description: "Queryable JSON index derived from append-only audit logs.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/audit/index.json"],
    assurance: "observed",
    writers: ["lib/audit-log.sh", "web/lib/middleware/audit-logger.ts"],
    readers: ["lib/audit-log.sh", "web/app/api/audit/route.ts"],
    samples: { root: "namespace", patterns: [["audit", "index.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "global-circuit-breaker",
    name: "Global Circuit Breaker",
    category: "system",
    description: "Host-wide execution kill switch, concurrency ceiling, active count, and daily run count.",
    scope: "global",
    format: "json",
    storage: ["{globalRoot}/circuit-breaker.json"],
    assurance: "typed",
    typePaths: ["web/lib/api/circuit-breaker.ts"],
    writers: ["web/lib/api/circuit-breaker.ts"],
    readers: ["web/lib/api/circuit-breaker.ts"],
    samples: { root: "global", patterns: [["circuit-breaker.json"]], format: "json" },
  }),
  shape({
    id: "system-settings",
    name: "System Settings",
    category: "system",
    description: "Namespace execution concurrency ceiling and task auto-run switch.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/system-settings.json"],
    assurance: "typed",
    typePaths: ["web/lib/system/system-settings.ts"],
    writers: ["web/lib/system/system-settings.ts"],
    readers: ["web/lib/system/system-settings.ts", "web/app/api/system/settings/route.ts"],
    samples: { root: "namespace", patterns: [["system-settings.json"]], format: "json" },
  }),
  shape({
    id: "data-retention-settings",
    name: "Data Retention Settings",
    category: "system",
    description: "Namespace retention policies for run history, event logs, and audit logs.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/settings/data.json"],
    assurance: "typed",
    typePaths: ["web/app/api/settings/data/route.ts"],
    writers: ["web/app/api/settings/data/route.ts"],
    readers: ["web/app/api/settings/data/route.ts"],
    samples: { root: "namespace", patterns: [["settings", "data.json"]], format: "json" },
  }),
  shape({
    id: "pinned-runs",
    name: "Pinned Runs",
    category: "system",
    description: "Namespace-wide ordered run ID list filtered through run ACLs on read.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/settings/pinned-runs.json"],
    assurance: "typed",
    typePaths: ["web/app/api/runs/pinned/route.ts"],
    writers: ["web/app/api/runs/pinned/route.ts"],
    readers: ["web/app/api/runs/pinned/route.ts"],
    samples: { root: "namespace", patterns: [["settings", "pinned-runs.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "debug-run-state",
    name: "Debug Run State",
    category: "system",
    description: "Per-run debugger status, current step, step records, breakpoints, and last control action.",
    scope: "project",
    format: "json",
    storage: ["{runtimeRoot}/debug/{runId}.json"],
    assurance: "typed",
    typePaths: ["web/app/api/chains/[id]/debug/route.ts"],
    writers: ["web/app/api/chains/[id]/debug/route.ts"],
    readers: ["web/app/api/chains/[id]/debug/route.ts"],
    samples: { root: "project", patterns: [["debug", "*.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "development-root-secret",
    name: "Development Root Secret",
    category: "system",
    description: "Local-development root secret created when no externally provisioned authentication secret exists.",
    scope: "global",
    format: "text",
    storage: ["{globalRoot}/data/dev-secret"],
    assurance: "enforced",
    validatorPaths: ["web/lib/secrets/dev-secret.ts"],
    writers: ["web/lib/secrets/dev-secret.ts"],
    readers: ["web/lib/secrets/dev-secret.ts"],
    samples: { root: "global", patterns: [["data", "dev-secret"]], format: "text" },
    sensitive: true,
    notes: ["The scanner records only byte size for text files; it never reads or returns this value."],
  }),
  shape({
    id: "system-log",
    name: "System Log Record",
    category: "system",
    description: "Append-only structured runtime log entries.",
    scope: "project",
    format: "jsonl",
    storage: ["{runtimeRoot}/logs/system.jsonl"],
    assurance: "observed",
    writers: ["web/lib/system/system-logger.ts"],
    readers: ["web/lib/system/system-logger.ts", "web/app/api/system/logs/route.ts"],
    samples: { root: "project", patterns: [["logs", "system.jsonl"]], format: "jsonl" },
  }),
  shape({
    id: "runtime-profiler",
    name: "Agent Runtime Profile",
    category: "system",
    description: "Per-session timing, resource samples, API calls, token totals, and terminal status.",
    scope: "project",
    format: "json",
    storage: ["{runtimeRoot}/profiles/{session}.json"],
    assurance: "observed",
    writers: ["lib/profiler.sh"],
    readers: ["lib/profiler.sh", "web/lib/config.ts"],
    samples: { root: "project", patterns: [["profiles", "*.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "performance-metrics",
    name: "Run Performance Metrics",
    category: "system",
    description: "Per-run agent timing, model calls, token counts, resource samples, and cost estimates.",
    scope: "project",
    format: "json",
    storage: ["{runtimeRoot}/metrics/{runId}/performance.json", "{runRoot}/{runId}/performance.json (comparison reader)"],
    assurance: "observed",
    writers: ["lib/performance.sh"],
    readers: ["lib/performance.sh", "web/app/api/performance/route.ts", "web/app/api/runs/compare/route.ts"],
    samples: { root: "project", patterns: [["metrics", "*", "performance.json"], ["runs", "*", "performance.json"]], format: "json" },
    sensitive: true,
    notes: ["The shell writer follows project metrics; the performance API uses namespace metrics and the compare API reads run-local performance.json."],
  }),
  shape({
    id: "chain-watcher-runtime",
    name: "Chain Watcher Runtime",
    category: "system",
    description: "Cross-chain watcher singleton PID lock and append-only daemon log.",
    scope: "project",
    format: "mixed",
    storage: ["{runtimeRoot}/runtime/chain-watcher/running-{namespaceId}/pid", "{runtimeRoot}/runtime/chain-watcher/watcher.log"],
    assurance: "observed",
    writers: ["lib/chain-event-watcher.sh"],
    readers: ["lib/chain-event-watcher.sh", "web/lib/runner-v2/bootstrap-executor.ts"],
    samples: { root: "project", patterns: [["runtime", "chain-watcher", "watcher.log"]], format: "text" },
  }),
  shape({
    id: "background-worker-state",
    name: "Background Worker State",
    category: "system",
    description: "Background worker PID, running/stopped state, timestamps, and health metadata.",
    scope: "project",
    format: "json",
    storage: ["{runtimeRoot}/state/background-worker.json", "{runtimeRoot}/state/background-worker.pid"],
    assurance: "typed",
    typePaths: ["web/lib/system/background-worker-state.ts"],
    writers: ["web/lib/system/background-worker-state.ts", "web/server/background-worker.cjs"],
    readers: ["web/lib/system/background-worker-state.ts"],
    samples: { root: "project", patterns: [["state", "background-worker.json"]], format: "json" },
  }),
  shape({
    id: "retry-state",
    name: "Organization Retry and Circuit State",
    category: "system",
    description: "Per-chain retry policy, per-run retry state, and per-agent circuit breaker state.",
    scope: "organization",
    format: "json",
    storage: ["{orgRoot}/retry/{chainId}-config.json", "{orgRoot}/retry/{runId}-state.json", "{orgRoot}/retry/circuit-{chainId}-{agent}.json"],
    assurance: "typed",
    typePaths: ["web/lib/runs/retry-types.ts", "web/lib/runs/retry-storage.ts"],
    writers: ["web/lib/runs/retry-storage.ts"],
    readers: ["web/lib/runs/retry-storage.ts"],
    samples: { root: "organization", patterns: [["retry", "*.json"]], format: "json" },
  }),
  shape({
    id: "runner-retry-state",
    name: "Runner Retry State",
    category: "system",
    description: "Shell and runner-v2 per-agent attempt counters plus circuit breaker state.",
    scope: "run",
    format: "mixed",
    storage: ["{runRoot}/{runId}/state/retry/retry_{agentId}.count", "{runRoot}/{runId}/state/retry/circuit_{chain}_{agentId}.json", "{runtimeRoot}/state/retry/*"],
    assurance: "typed",
    typePaths: ["web/lib/runner-v2/adapters.ts", "web/lib/runner-v2/retry-plan.ts"],
    writers: ["web/lib/runner-v2/adapters.ts", "lib/chain-runner-complete.sh", "lib/retry-utils.sh"],
    readers: ["web/lib/runner-v2/adapters.ts", "lib/error-handling.sh", "lib/retry-utils.sh"],
    samples: {
      root: "project",
      patterns: [["runs", "*", "state", "retry", "*.json"], ["state", "retry", "*.json"]],
      format: "json",
    },
    notes: ["Numeric .count files are part of the contract but the live field scanner samples the JSON circuit records."],
  }),
  shape({
    id: "breakpoints",
    name: "Chain Breakpoints",
    category: "system",
    description: "Debug breakpoints keyed by chain and agent/event location.",
    scope: "project",
    format: "json",
    storage: ["{runtimeRoot}/debug/breakpoints/{chainId}/breakpoints.json"],
    assurance: "typed",
    typePaths: ["web/lib/runs/breakpoint-store.ts"],
    writers: ["web/lib/runs/breakpoint-store.ts"],
    readers: ["web/lib/runs/breakpoint-store.ts"],
    samples: { root: "project", patterns: [["debug", "breakpoints", "*", "breakpoints.json"]], format: "json" },
  }),
  shape({
    id: "token-usage",
    name: "Token Usage",
    category: "system",
    description: "Per-run/per-agent token records and the aggregate token index.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/tokens/_index.json", "{namespaceRoot}/tokens/{runId}/{agentId}.json"],
    assurance: "typed",
    typePaths: ["web/lib/system/token-store.ts"],
    writers: ["web/lib/system/token-store.ts", "web/app/api/tokens/record/route.ts"],
    readers: ["web/lib/system/token-store.ts", "web/app/api/runs/[id]/cost/route.ts"],
    samples: { root: "namespace", patterns: [["tokens", "_index.json"], ["tokens", "*", "*.json"]], format: "json" },
  }),
  shape({
    id: "onboarding-state",
    name: "Onboarding State",
    category: "system",
    description: "Per-user onboarding checklist and completion state.",
    scope: "namespace",
    format: "json",
    storage: ["{namespaceRoot}/settings/onboarding/{userId}.json"],
    assurance: "typed",
    typePaths: ["web/lib/system/onboarding-storage.ts"],
    writers: ["web/lib/system/onboarding-storage.ts"],
    readers: ["web/lib/system/onboarding-storage.ts"],
    samples: { root: "namespace", patterns: [["settings", "onboarding", "*.json"]], format: "json" },
    sensitive: true,
  }),
  shape({
    id: "external-conversation-transcript",
    name: "External Conversation Transcript",
    category: "system",
    description: "CLI-owned JSONL conversation transcript resolved and selectively edited by Mentiko conversation APIs.",
    scope: "external",
    format: "jsonl",
    storage: ["CLI-specific transcript roots such as ~/.claude/projects/{encodedCwd}/{conversationId}.jsonl"],
    assurance: "open",
    typePaths: ["web/lib/runs/session-log-resolver.ts"],
    writers: ["web/app/api/conversations/[id]/route.ts"],
    readers: ["web/app/api/conversations/[id]/route.ts", "web/lib/runs/session-log-resolver.ts"],
    sensitive: true,
    notes: ["Ownership and schema belong to the external CLI; Mentiko does not scan transcript contents in this catalog."],
  }),
  shape({
    id: "kollab-integration-config",
    name: "Kollab Integration Config",
    category: "system",
    description: "Kollab active profile plus Mentiko MCP server registration maintained outside the Mentiko data root.",
    scope: "external",
    format: "json",
    storage: ["~/.kollab/config.json", "~/.kollab/mcp/mcp_settings.json"],
    assurance: "typed",
    typePaths: ["web/lib/agents/mentiko-engine-profile.ts", "web/lib/process-manager.ts"],
    writers: ["web/lib/agents/mentiko-engine-profile.ts", "web/app/api/kollabor/profiles/active/route.ts", "web/app/api/kollabor/setup/mentiko/route.ts", "web/lib/process-manager.ts"],
    readers: ["web/app/api/kollabor/profiles/active/route.ts", "web/lib/process-manager.ts"],
    sensitive: true,
    notes: ["MCP environment entries can contain authentication material; no values are exposed by the catalog."],
  }),
  shape({
    id: "process-manager-config",
    name: "Process Manager Config",
    category: "system",
    description: "Managed service graph, commands, dependencies, restart policy, health checks, and environment.",
    scope: "external",
    format: "json",
    storage: ["web/processes.dev.json", "web/lib/processes.json", "/opt/mentiko/processes.json"],
    assurance: "typed",
    typePaths: ["web/lib/process-manager.ts"],
    writers: ["web/lib/process-manager.ts", "deployment tooling"],
    readers: ["web/lib/process-manager.ts"],
    sensitive: true,
    notes: ["This is code/deployment configuration rather than tenant data, so the runtime scanner does not open it."],
  }),
  shape({
    id: "terminal-token-registration",
    name: "Terminal Token Registration",
    category: "system",
    description: "Short-lived per-user websocket terminal token registration plus legacy static token fallback.",
    scope: "external",
    format: "mixed",
    storage: ["~/.pty-manager/ws-token-register-{prefix}.json", "~/.pty-manager/ws-token"],
    assurance: "typed",
    typePaths: ["web/app/api/terminal/token/route.ts"],
    writers: ["web/app/api/terminal/token/route.ts", "ws-terminal scanner"],
    readers: ["web/app/api/terminal/token/route.ts", "ws-terminal scanner"],
    sensitive: true,
    notes: ["Registration JSON is an atomic handoff deleted by the scanner; the catalog never opens either token file."],
  }),
  shape({
    id: "linux-workspace-user-config",
    name: "Linux Workspace User Config",
    category: "system",
    description: "Tenant-VPS Linux user shell environment and authorized SSH key list managed by Mentiko.",
    scope: "external",
    format: "text",
    storage: ["/home/{username}/.bashrc", "/home/{username}/.ssh/authorized_keys"],
    assurance: "enforced",
    validatorPaths: ["web/lib/workspaces/linux-users.ts"],
    writers: ["web/lib/workspaces/linux-users.ts"],
    readers: ["web/lib/workspaces/linux-users.ts", "Linux login and SSH services"],
    sensitive: true,
    notes: ["These host-managed files are cataloged for ownership but are never scanned from the web process."],
  }),
  shape({
    id: "pty-session-ownership",
    name: "PTY Session Ownership",
    category: "system",
    description: "Durable session-to-user ownership map outside the Mentiko data root.",
    scope: "external",
    format: "json",
    storage: ["~/.pty-manager/session-owners.json"],
    assurance: "typed",
    typePaths: ["web/lib/pty/session-owners.ts"],
    writers: ["web/lib/pty/session-owners.ts"],
    readers: ["web/lib/pty/session-owners.ts"],
    sensitive: true,
    notes: ["This file is not covered by namespace backup/export semantics."],
  }),
  shape({
    id: "mcp-session-sidecar",
    name: "MCP Session Sidecar",
    category: "system",
    description: "Refresh-token sidecar used by the standalone Mentiko MCP bridge.",
    scope: "external",
    format: "json",
    storage: ["~/.mentiko/mcp/session.json"],
    assurance: "typed",
    typePaths: ["lib/mentiko-mcp/handlers/session-store.ts"],
    writers: ["lib/mentiko-mcp/handlers/session-store.ts"],
    readers: ["lib/mentiko-mcp/handlers/session-store.ts"],
    sensitive: true,
  }),
];

/**
 * Store-like modules discovered by the catalog coverage test but intentionally
 * excluded because they persist browser UI state or are read-only projections.
 */
export const DATA_SHAPE_SOURCE_EXCLUSIONS: Record<string, string> = {
  "web/app/api/chains/[id]/git/init/route.ts": "writes workspace Git metadata and .gitignore, not a Mentiko-owned data contract",
  "web/app/api/fs/create/route.ts": "generic user workspace file creation; content shape is intentionally open",
  "web/app/api/fs/file/route.ts": "generic user workspace file editor; content shape is intentionally open",
  "web/app/api/gdpr/export/route.ts": "imports filesystem helpers but returns a derived response without persisting an artifact",
  "web/app/api/health/route.ts": "imports write helpers for a transient filesystem health probe, not durable data",
  "web/app/api/mentiko-mcp/ops/files/route.ts": "generic user workspace file editor; content shape is intentionally open",
  "web/lib/agents/agents-store.ts": "client data-fetching store; agent persistence is cataloged through agent-definition",
  "web/lib/chains/chains-store.ts": "client data-fetching store; chain persistence is cataloged through chain-definition",
  "web/lib/hooks/use-snooze-state.ts": "React hook state; schedule persistence is cataloged through schedule",
  "web/lib/i18n/locale-store.ts": "browser localStorage preference, outside server/runtime persistence scope",
  "web/lib/notifications/notifications-store.ts": "client Zustand state; server notification persistence is cataloged separately",
  "web/lib/runs/run-state.ts": "derived runtime overlay reader; persisted run and agent state are cataloged separately",
  "web/lib/runs/runs-store.ts": "client/reader projection; run persistence is cataloged through run-record",
  "web/lib/tasks/auto-run-state.ts": "pure task auto-run state reducer, not a persistence writer",
  "web/lib/ui/editor-store.ts": "browser Zustand/localStorage state, outside server/runtime persistence scope",
  "web/lib/ui/kollabor-bar-store.ts": "browser Zustand/localStorage state, outside server/runtime persistence scope",
  "web/lib/data-shapes/runtime-catalog.ts": "read-only catalog inspector; it opens SQLite databases with readonly true",
  "web/lib/workspaces/demo-workspace.ts": "seeds arbitrary demo source files outside Mentiko-owned runtime data",
};
