"use client";

import { PageBanner } from "@/components/ui/page-banner";
import { MagicStarFilled, LinkFilled, BotMessageSquare } from "@aliimam/icons";

const CodeBlock = ({ children }: { children: string }) => (
  <pre className="bg-muted rounded-md p-3 font-mono text-[11px] text-foreground/70 whitespace-pre overflow-x-auto mb-4">
    {children}
  </pre>
);

export default function GenerationDocPage() {
  return (
    <div>
      <PageBanner
        title="Generation"
        subtitle="AI-powered chain generation from natural language descriptions. Describe what you want, and the system builds a complete chain with agents."
        icon={MagicStarFilled}
        sectionColor="#f59e0b"
        actions={[
          { label: "Generation", href: "/generation", icon: MagicStarFilled, iconColor: "#b07ee8" },
          { label: "Chains", href: "/chains", icon: LinkFilled, iconColor: "#b07ee8" },
          { label: "Agents", href: "/agents", icon: BotMessageSquare, iconColor: "#b07ee8" },
        ]}
      />
      <div className="px-6 pb-6 max-w-3xl">

      <section className="mb-6">
        <h2 className="text-sm font-medium mb-2">Generation Flow</h2>
        <p className="text-xs text-foreground/60 leading-relaxed mb-3">
          Chain generation happens asynchronously via background jobs:
        </p>
        <div className="bg-card rounded-md p-3 text-xs text-foreground/60 space-y-1">
          <div>1. Describe task - natural language input</div>
          <div>2. Create generation job - queued for processing</div>
          <div>3. LLM generates chain - uses agent catalog for context</div>
          <div>4. Post-process - extracts inline agents to $ref</div>
          <div>5. Poll for status - job updates in real-time</div>
          <div>6. Review and save - edit or use generated chain</div>
        </div>
      </section>

      <section className="mb-6">
        <h2 className="text-sm font-medium mb-2">Agent Catalog</h2>
        <p className="text-xs text-foreground/60 leading-relaxed mb-3">
          The generation system indexes available agents to use in generated chains:
        </p>
        <div className="bg-card rounded-md p-3 text-xs text-foreground/60 space-y-1">
          <div>Scans namespace agents directory</div>
          <div>Indexes agent IDs, names, descriptions</div>
          <div>Uses descriptions to match task requirements</div>
          <div>Injects $ref references instead of inline definitions</div>
        </div>
      </section>

      <section className="mb-6">
        <h2 className="text-sm font-medium mb-2">Post-Processing</h2>
        <p className="text-xs text-foreground/60 leading-relaxed mb-3">
          Generated chains are optimized before saving:
        </p>
        <div className="bg-card rounded-md p-3 text-xs text-foreground/60 space-y-1">
          <div>Inline agent extraction - creates standalone agent files</div>
          <div>$ref conversion - replaces inline with references</div>
          <div>Duplicate deduplication - reuses existing agents</div>
          <div>Format validation - ensures valid chain JSON</div>
        </div>
      </section>

      <section className="mb-6">
        <h2 className="text-sm font-medium mb-2">Generation Templates</h2>
        <p className="text-xs text-foreground/60 leading-relaxed mb-3">
          Customize how chains are generated by editing templates:
        </p>
        <CodeBlock>{`# Template: chain_generation
# Stored in: namespaces/{id}/generation-templates/

You are a chain builder. Given a task description, create a chain
that accomplishes it.

Available agents:
{{AGENT_CATALOG}}

Task: {{USER_TASK}}

Output a valid chain.json with:
- name, version, description
- agents array (use $ref for known agents)
- proper triggers/emits wiring`}</CodeBlock>
      </section>

      <section className="mb-6">
        <h2 className="text-sm font-medium mb-2">Job Status Polling</h2>
        <p className="text-xs text-foreground/60 leading-relaxed mb-3">
          Generation jobs run asynchronously. Poll for updates:
        </p>
        <CodeBlock>{`# Create generation job
POST /api/generate
{
  "task": "Build a deploy pipeline with tests"
}
# Returns: { jobId: "gen_123" }

# Poll job status
GET /api/generate/{jobId}
# Returns: { status: "pending"|"running"|"completed"|"failed", result? }

# Completed result
{
  "status": "completed",
  "result": {
    "chain": { /* chain.json */ },
    "agents": [
      { "id": "tester", "name": "Tester", ... }
    ]
  }
}`}</CodeBlock>
      </section>

      <section className="mb-6">
        <h2 className="text-sm font-medium mb-2">Built-in Templates</h2>
        <p className="text-xs text-foreground/60 leading-relaxed mb-3">
          Default templates included with the platform:
        </p>
        <div className="bg-card rounded-md p-3 space-y-1 text-xs text-foreground/60">
          <div><code className="text-foreground/70">chain_generation</code> - main chain builder</div>
          <div><code className="text-foreground/70">agent_extraction</code> - inline to $ref converter</div>
          <div><code className="text-foreground/70">agent_refinement</code> - prompt optimizer</div>
          <div><code className="text-foreground/70">chain_validation</code> - JSON schema validator</div>
        </div>
      </section>

      <section className="mb-6">
        <h2 className="text-sm font-medium mb-2">Task-Driven Generation</h2>
        <p className="text-xs text-foreground/60 leading-relaxed mb-3">
          Generate chains directly from native tasks:
        </p>
        <div className="bg-card rounded-md p-3 text-xs text-foreground/60 space-y-1">
          <div>From task detail page, click &quot;Generate Chain&quot;</div>
          <div>Task title and description populate the prompt</div>
          <div>Generated chain links back to originating task</div>
          <div>Auto-run on task close if workspace enabled</div>
        </div>
      </section>

      <section className="mb-6">
        <h2 className="text-sm font-medium mb-2">Generation Settings</h2>
        <p className="text-xs text-foreground/60 leading-relaxed mb-3">
          Configure generation behavior in settings:
        </p>
        <div className="bg-card rounded-md p-3 text-xs text-foreground/60 space-y-1">
          <div>Default model - LLM for generation</div>
          <div>Agent catalog scope - which agents to reference</div>
          <div>Max agents - limit generated chain complexity</div>
          <div>Auto-extract - always extract inline agents</div>
        </div>
      </section>
      </div>
    </div>
  );
}
