#!/bin/bash
# Typed runtime-path boundary.
#
# Shell only locates the checked-in typed bundle, sources its safe export
# projection, and retains legacy function names that forward to typed owners.

_CONFIG_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_CONFIG_CODE_ROOT="${MENTIKO_CODE_ROOT:-$(cd "$_CONFIG_SCRIPT_DIR/.." && pwd)}"
_CONFIG_RUNTIME_CLI="$_CONFIG_CODE_ROOT/lib/runner-runtime-paths.js"

if [[ ! -f "$_CONFIG_RUNTIME_CLI" ]]; then
  echo "mentiko: typed runtime-path bundle missing: $_CONFIG_RUNTIME_CLI" >&2
  return 1 2>/dev/null || exit 1
fi

_config_runtime_exports="$(MENTIKO_CODE_ROOT="$_CONFIG_CODE_ROOT" node "$_CONFIG_RUNTIME_CLI" shell-exports)" || {
  echo "mentiko: typed runtime-path export failed" >&2
  return 1 2>/dev/null || exit 1
}
# Output is generated by formatRuntimePathExports: fixed variable names plus
# single-quoted primitive values. No runtime data is parsed or reconstructed in shell.
eval "$_config_runtime_exports"
unset _config_runtime_exports _CONFIG_RUNTIME_CLI _CONFIG_CODE_ROOT _CONFIG_SCRIPT_DIR

# Definition contracts belong to the typed runtime. These helpers remain only
# as invocation boundaries for scripts that need a primitive workspace value.
if [[ -f "$LIB_DIR/chain-contract-client.sh" ]]; then
  source "$LIB_DIR/chain-contract-client.sh"
fi

chain_config() {
  local chain_file="$1"
  local key="$2"
  if [[ -f "$chain_file" ]]; then
    chain_contract_raw_field "$chain_file" "$AGENTS_DIR" "$CONFIG_PROFILES_DIR" "$key" 2>/dev/null || true
  fi
}

chain_id_from_name() {
  local name="$1"
  echo "$name" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-'
}

workspace_type() {
  local chain_file="$1"
  chain_contract_field "$chain_file" "$AGENTS_DIR" "$CONFIG_PROFILES_DIR" "workspace.type" 2>/dev/null || echo "local"
}

workspace_ssh_config() {
  local chain_file="$1"
  local field="$2"
  chain_contract_field "$chain_file" "$AGENTS_DIR" "$CONFIG_PROFILES_DIR" "workspace.ssh.${field}" 2>/dev/null || true
}

workspace_docker_config() {
  local chain_file="$1"
  local field="$2"
  chain_contract_field "$chain_file" "$AGENTS_DIR" "$CONFIG_PROFILES_DIR" "workspace.docker.${field}" 2>/dev/null || true
}
