"use client";

import { useState } from "react";
import { cn } from "@/lib/utils";
import { replyToTool } from "@/lib/ai-engine/mentiko-mcp-bar-client";
import { ShieldTickFilled, Warning2Filled } from "@aliimam/icons";

interface KollaborAskPromptProps {
  toolId: string;
  kind: "ask_confirm" | "ask_input" | "ask_choice";
  prompt: string;
  options?: unknown[];
  placeholder?: string;
  result?: unknown;
  onRespond: (result: unknown) => void;
}

// detect if this is a permission gate prompt (generated by checkPermission in server.ts)
function isPermissionPrompt(prompt: string): { isGate: boolean; toolName: string; preview: string; isHighRisk: boolean } {
  const match = prompt.match(/^allow ([^\?]+)\?(?:\s*\(high risk[^)]*\))?\s*\n\n([\s\S]*)$/);
  if (!match) return { isGate: false, toolName: "", preview: "", isHighRisk: false };
  return {
    isGate: true,
    toolName: match[1].trim(),
    preview: match[2].trim(),
    isHighRisk: prompt.includes("high risk"),
  };
}

function normalizeOption(opt: unknown): { value: string; label: string; description?: string } {
  if (typeof opt === "string") return { value: opt, label: opt };
  if (opt && typeof opt === "object") {
    const record = opt as Record<string, unknown>;
    const rawValue = record.value ?? opt;
    const rawLabel = record.label ?? record.value ?? opt;
    return {
      value: optionText(rawValue),
      label: optionText(rawLabel),
      description:
        typeof record.description === "string" ? record.description : undefined,
    };
  }
  return { value: String(opt), label: String(opt) };
}

function optionText(value: unknown): string {
  if (typeof value === "string") return value;
  const encoded = JSON.stringify(value);
  return typeof encoded === "string" ? encoded : String(value);
}

export function KollaborAskPrompt({
  toolId,
  kind,
  prompt,
  options,
  placeholder,
  result,
  onRespond,
}: KollaborAskPromptProps) {
  const [inputValue, setInputValue] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [replyError, setReplyError] = useState<string | null>(null);

  const resolved = result !== undefined;

  const handleRespond = async (value: unknown) => {
    if (resolved || submitting) return;
    setSubmitting(true);
    setReplyError(null);
    try {
      await replyToTool(toolId, value);
      onRespond(value);
    } catch {
      setReplyError("failed to send reply");
    } finally {
      setSubmitting(false);
    }
  };

  // permission gate: special styling for the checkPermission ask_choice
  if (kind === "ask_choice") {
    const gate = isPermissionPrompt(prompt);
    if (gate.isGate) {
      return <PermissionGate
        toolName={gate.toolName}
        preview={gate.preview}
        isHighRisk={gate.isHighRisk}
        options={(options || []).map(normalizeOption)}
        resolved={resolved}
        result={result}
        submitting={submitting}
        onRespond={handleRespond}
      />;
    }
  }

  // plain ask_choice
  if (kind === "ask_choice") {
    return (
      <div className="flex flex-col gap-2 max-w-[85%] self-start">
        <div className="text-xs text-foreground/80 px-0.5">{prompt}</div>
        {!resolved ? (
          <div className="grid grid-cols-1 gap-1.5 w-full">
            {(options || []).map(normalizeOption).map((opt, index) => (
              <button
                key={`${opt.value}-${index}`}
                onClick={() => handleRespond(opt.value)}
                disabled={submitting}
                className="flex flex-col items-start px-3 py-2 rounded-xl bg-muted/60 hover:bg-muted border border-border/30 transition-colors text-left"
              >
                <span className="text-xs font-medium">{opt.label}</span>
                {opt.description && (
                  <span className="text-[10px] text-muted-foreground">{opt.description}</span>
                )}
              </button>
            ))}
          </div>
        ) : (
          <ResolvedBadge value={result} />
        )}
        {replyError && (
          <div className="text-[10px] text-destructive px-0.5">
            Could not send that reply. Try again.
          </div>
        )}
      </div>
    );
  }

  // ask_confirm
  if (kind === "ask_confirm") {
    const confirmOpts = options && options.length > 0 ? options.map(normalizeOption) : [{ value: "yes", label: "yes" }, { value: "no", label: "no" }];
    return (
      <div className="flex flex-col gap-2 max-w-[85%] self-start">
        <div className="text-xs text-foreground/80 px-0.5">{prompt}</div>
        {!resolved ? (
          <div className="flex gap-2">
            {confirmOpts.map((opt, index) => (
              <button
                key={`${opt.value}-${index}`}
                onClick={() => handleRespond(opt.value)}
                disabled={submitting}
                className={cn(
                  "h-7 px-3 rounded-lg text-xs font-medium transition-colors",
                  opt.value === "yes" || opt.value === "approve"
                    ? "bg-foreground text-background hover:opacity-90"
                    : "bg-muted text-foreground hover:bg-muted/80"
                )}
              >
                {opt.label}
              </button>
            ))}
          </div>
        ) : (
          <ResolvedBadge value={result} />
        )}
        {replyError && (
          <div className="text-[10px] text-destructive px-0.5">
            Could not send that reply. Try again.
          </div>
        )}
      </div>
    );
  }

  // ask_input
  return (
    <div className="flex flex-col gap-2 max-w-[85%] self-start w-full">
      <div className="text-xs text-foreground/80 px-0.5">{prompt}</div>
      {!resolved ? (
        <div className="flex items-center gap-2">
          <input
            autoFocus
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && inputValue.trim()) handleRespond(inputValue.trim());
            }}
            placeholder={placeholder || "type your answer..."}
            className="flex-1 min-w-0 bg-muted/30 border border-border/40 rounded-lg px-3 py-1.5 text-xs outline-none focus:border-primary/40 transition-colors"
          />
          <button
            onClick={() => handleRespond(inputValue.trim())}
            disabled={!inputValue.trim() || submitting}
            className="h-7 px-3 rounded-lg bg-foreground text-background text-xs font-medium hover:opacity-90 transition-opacity disabled:opacity-40"
          >
            send
          </button>
        </div>
      ) : (
        <ResolvedBadge value={result} />
      )}
      {replyError && (
        <div className="text-[10px] text-destructive px-0.5">
          Could not send that reply. Try again.
        </div>
      )}
    </div>
  );
}

function ResolvedBadge({ value }: { value: unknown }) {
  const text = typeof value === "string" ? value : JSON.stringify(value);
  const isDeny = text === "deny" || text === "no";
  return (
    <span className={cn(
      "inline-flex items-center rounded-full px-2.5 py-0.5 text-[10px] font-medium self-start",
      isDeny ? "bg-red-500/15 text-red-400" : "bg-green-500/15 text-green-400"
    )}>
      {text}
    </span>
  );
}

function PermissionGate({
  toolName,
  preview,
  isHighRisk,
  options,
  resolved,
  result,
  submitting,
  onRespond,
}: {
  toolName: string;
  preview: string;
  isHighRisk: boolean;
  options: { value: string; label: string }[];
  resolved: boolean;
  result: unknown;
  submitting: boolean;
  onRespond: (v: string) => void;
}) {
  const approveOpt = options.find((o) => o.value === "approve");
  const approveAlwaysOpt = options.find((o) => o.value === "approve always");
  const denyOpt = options.find((o) => o.value === "deny");

  return (
    <div className="max-w-[85%] self-start rounded-2xl bg-muted px-3.5 py-2.5 flex flex-col gap-2">
      {/* header */}
      <div className="flex items-center gap-2 text-sm text-foreground">
        <ShieldTickFilled className="w-4 h-4 shrink-0 text-foreground/60" />
        <span className="font-medium truncate">{toolName}</span>
        <span className="text-muted-foreground text-xs shrink-0">wants to run</span>
        <span className={cn(
          "ml-auto rounded-full px-2 py-0.5 text-[10px] shrink-0 font-medium",
          isHighRisk
            ? "bg-red-400/20 text-red-300"
            : "bg-amber-400/20 text-amber-300"
        )}>
          {isHighRisk ? "high" : "medium"}
        </span>
      </div>

      {/* args preview */}
      {preview && (
        <pre className="font-mono text-[10px] bg-background/50 rounded-lg px-2.5 py-2 whitespace-pre-wrap break-all text-foreground/80 max-h-24 overflow-y-auto">
          {preview}
        </pre>
      )}

      {/* high risk warning */}
      {isHighRisk && !resolved && (
        <div className="flex items-center gap-1.5 text-[10px] text-red-300/80">
          <Warning2Filled className="w-3 h-3 shrink-0" />
          <span>destructive — must approve every time</span>
        </div>
      )}

      {/* buttons */}
      {!resolved ? (
        <div className="flex items-center gap-2 pt-0.5 flex-wrap">
          {approveOpt && (
            <button
              onClick={() => onRespond("approve")}
              disabled={submitting}
              className="h-7 rounded-lg text-xs px-3 bg-foreground text-background hover:opacity-90 transition-opacity font-medium disabled:opacity-50"
            >
              approve
            </button>
          )}
          {approveAlwaysOpt && (
            <button
              onClick={() => onRespond("approve always")}
              disabled={submitting}
              className="h-7 rounded-lg text-xs px-3 bg-muted-foreground/20 text-foreground hover:bg-muted-foreground/30 transition-colors disabled:opacity-50"
            >
              approve always
            </button>
          )}
          {denyOpt && (
            <button
              onClick={() => onRespond("deny")}
              disabled={submitting}
              className="h-7 rounded-lg text-xs px-3 bg-red-500/15 text-red-300 border border-red-500/25 hover:bg-red-500/25 transition-colors disabled:opacity-50"
            >
              deny
            </button>
          )}
        </div>
      ) : (
        <ResolvedBadge value={result} />
      )}
    </div>
  );
}
