"use client";

import { useState } from "react";
import {
  RotateFilled as Loader2,
  ExportFilled as Save,
  DocumentTextFilled as FileText,
  InfoCircleFilled as AlertCircle,
} from "@aliimam/icons";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useNamespaceFetch } from "@/lib/use-namespace-fetch";
import { getApiErrorMessage } from "@/lib/api-client";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import type { ArtifactType } from "@/lib/artifact-template-storage";

const ARTIFACT_TYPES: { value: ArtifactType; label: string }[] = [
  { value: "markdown", label: "Markdown" },
  { value: "json", label: "JSON" },
  { value: "code", label: "Code" },
  { value: "patch", label: "Patch" },
  { value: "csv", label: "CSV" },
  { value: "text", label: "Text" },
  { value: "image", label: "Image" },
];

const TEMPLATE_PLACEHOLDERS: Record<ArtifactType, string> = {
  markdown: "# {{TITLE}}\n\n{{CONTENT}}",
  json: '{\n  "title": "{{TITLE}}",\n  "content": "{{CONTENT}}"\n}',
  code: "// {{DESCRIPTION}}\n// Generated by {{AGENT}}\n\n{{CODE}}",
  patch: `--- a/{{FILE}}
+++ b/{{FILE}}
@@ -1,3 +1,3 @@
-{{OLD}}
+{{NEW}}`,
  csv: "id,name,value\n1,{{NAME}},{{VALUE}}",
  text: "{{CONTENT}}",
  image: "[[Image output: {{FILENAME}}]]",
};

const SYNTAX_HINT = "use {{PLACEHOLDER}} syntax for variables";

interface ArtifactCreateDialogProps {
  open: boolean;
  onClose: () => void;
  onCreated: (template: { id: string; name: string }) => void;
}

export function ArtifactCreateDialog({
  open,
  onClose,
  onCreated,
}: ArtifactCreateDialogProps) {
  const { fetchWithNamespace } = useNamespaceFetch();
  const [id, setId] = useState("");
  const [name, setName] = useState("");
  const [type, setType] = useState<ArtifactType>("markdown");
  const [description, setDescription] = useState("");
  const [content, setContent] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  const handleClose = () => {
    setId("");
    setName("");
    setType("markdown");
    setDescription("");
    setContent("");
    setError("");
    onClose();
  };

  const handleTypeChange = (newType: ArtifactType) => {
    setType(newType);
    if (!content) {
      setContent(TEMPLATE_PLACEHOLDERS[newType]);
    }
  };

  const handleSave = async () => {
    setError("");

    if (!id.trim()) {
      setError("id is required");
      return;
    }
    if (!/^[a-zA-Z0-9_-]+$/.test(id)) {
      setError("id must contain only letters, numbers, hyphens, and underscores");
      return;
    }
    if (!name.trim()) {
      setError("name is required");
      return;
    }

    setSaving(true);
    try {
      const res = await fetchWithNamespace("/api/artifact-templates", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: id.trim(),
          name: name.trim(),
          type,
          description: description.trim(),
          content: content.trim(),
        }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(getApiErrorMessage(data, "Failed to create artifact template"));
      }

      onCreated({ id: id.trim(), name: name.trim() });
      handleClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={(v) => !v && handleClose()}>
      <DialogContent className="max-w-lg max-h-[85vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="text-sm font-medium flex items-center gap-2">
            <FileText className="h-4 w-4" />
            New Artifact Template
          </DialogTitle>
        </DialogHeader>

        {error && (
          <div className="flex items-start gap-2 p-3 bg-red-500/10 rounded-md text-xs text-red-400">
            <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
            <span>{error}</span>
          </div>
        )}

        <div className="flex-1 min-h-0 flex flex-col gap-3 overflow-y-auto">
          <div className="space-y-1">
            <label className="text-[10px] text-foreground/40 uppercase tracking-wide">
              id (slug)
            </label>
            <Input
              placeholder="e.g. technical-analysis"
              value={id}
              onChange={(e) => setId(e.target.value.toLowerCase().replace(/\s+/g, "-"))}
              className="text-sm bg-muted"
            />
          </div>

          <div className="space-y-1">
            <label className="text-[10px] text-foreground/40 uppercase tracking-wide">
              name
            </label>
            <Input
              placeholder="e.g. Technical Analysis"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="text-sm bg-muted"
            />
          </div>

          <div className="space-y-1">
            <label className="text-[10px] text-foreground/40 uppercase tracking-wide">
              type
            </label>
            <div className="flex flex-wrap gap-1.5">
              {ARTIFACT_TYPES.map((t) => (
                <button
                  key={t.value}
                  onClick={() => handleTypeChange(t.value)}
                  className={type === t.value
                    ? "px-2.5 py-1 rounded-md bg-foreground text-background text-xs font-medium"
                    : "px-2.5 py-1 rounded-md bg-muted text-foreground/60 text-xs hover:bg-accent/50"
                  }
                >
                  {t.label}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-[10px] text-foreground/40 uppercase tracking-wide">
              description
            </label>
            <Input
              placeholder="what this artifact produces"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="text-sm bg-muted"
            />
          </div>

          <div className="flex-1 min-h-0 flex flex-col space-y-1">
            <label className="text-[10px] text-foreground/40 uppercase tracking-wide">
              content template
            </label>
            <Textarea
              placeholder={TEMPLATE_PLACEHOLDERS[type]}
              value={content}
              onChange={(e) => setContent(e.target.value)}
              className="flex-1 min-h-[180px] font-mono text-xs bg-muted resize-none"
              spellCheck={false}
            />
            <p className="text-[9px] text-foreground/30">
              {SYNTAX_HINT}
            </p>
          </div>
        </div>

        <div className="flex justify-end gap-2 pt-2">
          <Button variant="ghost" size="sm" onClick={handleClose}>
            Cancel
          </Button>
          <Button size="sm" onClick={handleSave} disabled={saving}>
            {saving ? (
              <>
                <Loader2 className="h-3 w-3 animate-spin" />
                <span className="ml-1.5">Creating...</span>
              </>
            ) : (
              <>
                <Save className="h-3 w-3" />
                <span className="ml-1.5">Create Template</span>
              </>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
