import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import path from "path";
import { orgPath } from "../config";
import type { ArtifactType } from "../types";

// ArtifactType lives canonically in ./types; re-export keeps the existing
// "@/lib/artifact-template-storage" import path working for consumers.
export type { ArtifactType };

export const ARTIFACT_TYPE_EXT: Record<ArtifactType, string> = {
  markdown: ".md",
  json: ".json",
  code: ".txt",
  patch: ".patch",
  csv: ".csv",
  text: ".txt",
  image: ".png",
};

export interface ArtifactTemplate {
  id: string;
  name: string;
  type: ArtifactType;
  description: string;
  content: string;
  updatedAt: string;
}

interface ArtifactTemplatesFile {
  templates: ArtifactTemplate[];
}

function getTemplatesPath(namespaceId: string, orgId: string): string {
  return orgPath(namespaceId, orgId, "artifact-templates.json");
}

const DEFAULT_TECHNICAL_ANALYSIS = `# Technical Analysis: {{SUBJECT}}

**Date**: {{DATE}}
**Agent**: {{AGENT}}
**Status**: DRAFT / REVIEW / FINAL

---

## Executive Summary

_2-3 sentences. What was analyzed, key finding, overall verdict._

---

## Scope

**In scope**: What was examined.
**Out of scope**: What was explicitly not examined and why.
**Methodology**: How the analysis was conducted (static review, dynamic testing, code reading, etc.).

---

## Findings

### CRITICAL — Must fix before proceeding

| ID | Description | Location | Impact |
|----|-------------|----------|--------|
| C-1 | | | |

### HIGH — Fix in this iteration

| ID | Description | Location | Impact |
|----|-------------|----------|--------|
| H-1 | | | |

### MEDIUM — Fix in next iteration

| ID | Description | Location | Impact |
|----|-------------|----------|--------|
| M-1 | | | |

### LOW — Improvements for consideration

| ID | Description | Notes |
|----|-------------|-------|
| L-1 | | |

---

## Risk Assessment

| Dimension | Level | Rationale |
|-----------|-------|-----------|
| Security | CRITICAL / HIGH / MEDIUM / LOW | |
| Performance | CRITICAL / HIGH / MEDIUM / LOW | |
| Reliability | CRITICAL / HIGH / MEDIUM / LOW | |
| Maintainability | CRITICAL / HIGH / MEDIUM / LOW | |
| Scalability | CRITICAL / HIGH / MEDIUM / LOW | |

**Overall Risk**: CRITICAL / HIGH / MEDIUM / LOW

---

## Root Cause Analysis

_For each critical/high finding: what caused it? Is it a pattern or one-off?_

---

## Recommendations

### Immediate (this sprint)

1. [Finding C-1] — Action required: ...
2. [Finding H-1] — Action required: ...

### Short-term (next 2 sprints)

1. ...

### Long-term (roadmap)

1. ...

---

## Appendix

### Evidence / Artifacts

- Code snippets, test outputs, benchmark results, etc.

### References

- Relevant documentation, CVEs, benchmarks, standards.

---

_Generated by {{AGENT}} on {{DATE}}_
`;

const DEFAULT_SECURITY_REPORT = `# Security Report: {{SUBJECT}}

**Date**: {{DATE}}
**Reviewed by**: {{AGENT}}
**Overall Risk**: CRITICAL / HIGH / MEDIUM / LOW

---

## Executive Summary

_One paragraph. What was reviewed, overall posture, most critical finding._

---

## Findings

Use severity: CRITICAL (exploitable now), HIGH (likely to be exploited), MEDIUM (defense-in-depth), LOW (hardening), INFO (best practice).

### CRITICAL

| ID | Vulnerability | Location | CVSS | Proof of Concept |
|----|---------------|----------|------|-----------------|
| SEC-C1 | | | | |

**Remediation**: ...

### HIGH

| ID | Vulnerability | Location | CVSS | Notes |
|----|---------------|----------|------|-------|
| SEC-H1 | | | | |

**Remediation**: ...

### MEDIUM

| ID | Vulnerability | Location | Notes |
|----|---------------|----------|-------|
| SEC-M1 | | | |

### LOW / INFO

| ID | Issue | Notes |
|----|-------|-------|
| SEC-L1 | | |

---

## OWASP Top 10 Coverage (2021)

- [ ] A01 Broken Access Control
- [ ] A02 Cryptographic Failures
- [ ] A03 Injection (SQL, XSS, Command)
- [ ] A04 Insecure Design
- [ ] A05 Security Misconfiguration
- [ ] A06 Vulnerable and Outdated Components
- [ ] A07 Identification and Authentication Failures
- [ ] A08 Software and Data Integrity Failures
- [ ] A09 Security Logging and Monitoring Failures
- [ ] A10 Server-Side Request Forgery (SSRF)

---

## Attack Surface Summary

| Entry Point | Auth Required | Rate Limited | Notes |
|-------------|--------------|-------------|-------|
| | | | |

---

## Threat Model

**Most likely attacker**: _internal / external / automated scanner_
**Most valuable asset**: _describe what an attacker would target_
**Most dangerous attack path**: _step-by-step_

---

## Remediation Roadmap

### Immediate (patch now)

1. [SEC-C1] ...

### Short-term (next sprint)

1. [SEC-H1] ...

### Backlog

1. [SEC-M1] ...

---

## Compliance Notes

_Note any relevant regulatory requirements: SOC2, GDPR, HIPAA, PCI-DSS, etc._

---

_Security review completed by {{AGENT}} on {{DATE}}_
`;

const DEFAULT_TASK_SUMMARY = `# Task Summary: {{TASK_TITLE}}

**Completed**: {{DATE}}
**Agent**: {{AGENT}}
**Duration**: _start time → end time_
**Status**: COMPLETE / PARTIAL / BLOCKED

---

## Objective

_What was this task trying to achieve? 1-2 sentences._

---

## What Was Done

_Concise narrative of actions taken. Be specific — name files, functions, commands._

1. ...
2. ...
3. ...

---

## Artifacts Produced

| File | Type | Description |
|------|------|-------------|
| | | |

---

## Key Decisions

| Decision | Alternatives Considered | Rationale |
|----------|------------------------|-----------|
| | | |

---

## Issues Encountered

| Issue | Impact | Resolution / Workaround |
|-------|--------|------------------------|
| | | |

---

## What Was NOT Done

_Explicitly list anything in scope that was not completed and why._

---

## Verification

- [ ] Changes compile / build successfully
- [ ] Tests pass (or none required)
- [ ] No regressions introduced
- [ ] Output reviewed for correctness

---

## Next Steps

_Ordered list for the downstream agent or human:_

1. ...
2. ...
3. ...

---

_Produced by {{AGENT}} on {{DATE}}_
`;

const DEFAULT_CODE_REVIEW = `# Code Review: {{SUBJECT}}

**Date**: {{DATE}}
**Reviewer**: {{AGENT}}
**PR / Branch**: _link or name_
**Verdict**: APPROVE / REQUEST CHANGES / COMMENT

---

## Summary

_1-2 sentences. Purpose of the change, overall quality verdict._

---

## Checklist

### Correctness
- [ ] Logic is correct and handles edge cases
- [ ] Error handling is appropriate
- [ ] No off-by-one errors or boundary condition bugs
- [ ] Concurrent/async code is safe

### Security
- [ ] No injection vulnerabilities (SQL, XSS, command injection)
- [ ] Secrets are not hardcoded
- [ ] Input validation at boundaries
- [ ] No path traversal or SSRF vectors

### Performance
- [ ] No N+1 queries or inefficient loops
- [ ] Memory usage is appropriate
- [ ] No unnecessary blocking operations
- [ ] Caching used appropriately

### Code Quality
- [ ] Code is readable and self-documenting
- [ ] Functions/classes have single responsibility
- [ ] No dead code or debug statements
- [ ] Consistent style with surrounding code

### Tests
- [ ] Unit tests cover new logic
- [ ] Edge cases are tested
- [ ] Tests are readable and maintainable
- [ ] Coverage is adequate

---

## Required Changes

| ID | File | Line | Issue | Suggestion |
|----|------|------|-------|------------|
| CR-1 | | | | |

---

## Suggestions (optional)

| File | Line | Suggestion |
|------|------|------------|
| | | |

---

## Praise

_What was done well? Be specific._

---

_Reviewed by {{AGENT}} on {{DATE}}_
`;

const DEFAULT_ADR = `# Architecture Decision Record: {{TITLE}}

**ID**: ADR-{{NUMBER}}
**Date**: {{DATE}}
**Status**: PROPOSED / ACCEPTED / DEPRECATED / SUPERSEDED
**Deciders**: {{AGENT}}

---

## Context and Problem Statement

_Describe the architectural context and the problem or question that needs to be addressed. Be specific — include constraints, requirements, and forces at play._

---

## Decision Drivers

- _Primary driver: ..._
- _Secondary driver: ..._
- _Constraint: ..._

---

## Considered Options

### Option 1: {{OPTION_1}}

**Description**: ...

**Pros**:
- ...

**Cons**:
- ...

**Risk**: LOW / MEDIUM / HIGH

---

### Option 2: {{OPTION_2}}

**Description**: ...

**Pros**:
- ...

**Cons**:
- ...

**Risk**: LOW / MEDIUM / HIGH

---

### Option 3: {{OPTION_3}} _(if applicable)_

**Description**: ...

---

## Decision

**Chosen option**: Option N — {{CHOSEN}}

**Rationale**: _Why this option was chosen over the alternatives._

---

## Consequences

### Positive

- ...

### Negative / Trade-offs

- ...

### Neutral

- ...

---

## Implementation Notes

_Any specifics about how to implement this decision correctly._

---

## Review Date

_When should this decision be revisited?_

---

_Decision recorded by {{AGENT}} on {{DATE}}_
`;

const DEFAULT_INCIDENT_REPORT = `# Incident Report: {{TITLE}}

**Date**: {{DATE}}
**Severity**: P0 / P1 / P2 / P3
**Status**: INVESTIGATING / MITIGATED / RESOLVED / POST-MORTEM
**Incident Commander**: {{AGENT}}

---

## Executive Summary

_2-3 sentences. What happened, who was affected, and current status._

---

## Timeline

All times in UTC.

| Time | Event |
|------|-------|
| {{DATE}} HH:MM | Incident detected |
| | |
| | Incident resolved |

---

## Impact

| Dimension | Impact |
|-----------|--------|
| Users affected | _number or %_ |
| Services affected | |
| Data affected | NONE / PARTIAL / FULL |
| Revenue impact | |
| Duration | _start → end_ |

---

## Root Cause

_Technical root cause. Be precise. "Increased latency" is not a root cause — "index missing on users.email causing full table scan" is._

**Primary cause**: ...
**Contributing factors**: ...

---

## Detection

**Detected by**: monitoring / user report / automated alert / manual observation
**Time to detection**: _from incident start_
**Why wasn't it caught earlier**: ...

---

## Response

### Actions Taken

1. _Time_ — Action taken — Person
2. ...

### What Worked

- ...

### What Didn't Work

- ...

---

## Resolution

_What fixed it? Be specific._

---

## Prevention

### Immediate (done or in-flight)

- [ ] ...

### Short-term (next sprint)

- [ ] ...

### Long-term (roadmap)

- [ ] ...

---

## Action Items

| Action | Owner | Due Date | Status |
|--------|-------|----------|--------|
| | | | |

---

_Report prepared by {{AGENT}} on {{DATE}}_
`;

const DEFAULT_PRD = `# Product Requirements: {{FEATURE_NAME}}

**Date**: {{DATE}}
**Author**: {{AGENT}}
**Status**: DRAFT / REVIEW / APPROVED
**Priority**: P0 / P1 / P2 / P3

---

## Overview

### Problem Statement

_What problem does this solve? Who has this problem? How often? What's the impact of not solving it?_

### Proposed Solution

_High-level description of what we're building._

### Success Metrics

| Metric | Baseline | Target | Measurement |
|--------|----------|--------|-------------|
| | | | |

---

## User Stories

### Primary

**As a** [type of user],
**I want to** [action],
**So that** [outcome / value].

**Acceptance Criteria**:
- [ ] ...
- [ ] ...

---

### Secondary

_Additional user stories..._

---

## Functional Requirements

### Must Have (MVP)

- REQ-1: ...
- REQ-2: ...

### Should Have

- REQ-3: ...

### Nice to Have

- REQ-4: ...

### Out of Scope

- ...

---

## Non-Functional Requirements

| Requirement | Specification |
|-------------|--------------|
| Performance | Response time < Xms at Y percentile |
| Availability | X% uptime |
| Security | Auth required, audit log |
| Scalability | Handles X users / Y requests |
| Accessibility | WCAG 2.1 AA |

---

## UX / Design Notes

_Key UX decisions, design references, wireframe links._

---

## Technical Considerations

_Architecture notes, API contracts, data model changes, dependencies, migration needs._

---

## Dependencies

| Dependency | Type | Status |
|------------|------|--------|
| | Team / Service / Feature | Blocked / In progress / Ready |

---

## Open Questions

| Question | Owner | Resolution |
|----------|-------|------------|
| | | |

---

## Timeline

| Milestone | Target Date | Notes |
|-----------|-------------|-------|
| Design approved | | |
| Development complete | | |
| QA complete | | |
| Launch | | |

---

_Requirements drafted by {{AGENT}} on {{DATE}}_
`;

const DEFAULT_RESEARCH_SUMMARY = `# Research Summary: {{TOPIC}}

**Date**: {{DATE}}
**Researcher**: {{AGENT}}
**Research Question**: _What specific question does this research answer?_

---

## TL;DR

_3-5 bullet points. The most important findings a decision-maker needs._

- ...
- ...
- ...

---

## Context

_Why was this research conducted? What decision does it inform?_

---

## Methodology

**Sources consulted**:
- Documentation: ...
- Code: ...
- External resources: ...
- Other: ...

**Time spent**: ...
**Confidence level**: HIGH / MEDIUM / LOW (how confident are we in these findings?)

---

## Findings

### Finding 1: {{TITLE}}

_Detailed explanation. Include evidence — quotes, code snippets, data._

**Evidence**:

\`\`\`
// code snippet or data
\`\`\`

---

### Finding 2: {{TITLE}}

_..._

---

### Finding 3: {{TITLE}}

_..._

---

## Comparison / Options Analysis

| Option | Pros | Cons | Recommendation |
|--------|------|------|----------------|
| | | | |

---

## Implications

_What do these findings mean for the project / decision at hand?_

---

## Recommendations

1. **Recommended approach**: ...
2. **Alternative if blocked**: ...
3. **Do not do**: ...

---

## Gaps / Unknowns

_What questions remain unanswered? What would require further research?_

- ...

---

## References

- [Title](url) — relevance
- ...

---

_Research by {{AGENT}} on {{DATE}}_
`;

function getDefaultTemplates(): ArtifactTemplate[] {
  const now = new Date().toISOString();
  return [
    {
      id: "technical-analysis",
      name: "Technical Analysis",
      type: "markdown",
      description: "Standard format for technical analysis reports",
      content: DEFAULT_TECHNICAL_ANALYSIS,
      updatedAt: now,
    },
    {
      id: "security-report",
      name: "Security Report",
      type: "markdown",
      description: "OWASP-structured security review output",
      content: DEFAULT_SECURITY_REPORT,
      updatedAt: now,
    },
    {
      id: "task-summary",
      name: "Task Summary",
      type: "markdown",
      description: "Agent completion handoff note",
      content: DEFAULT_TASK_SUMMARY,
      updatedAt: now,
    },
    {
      id: "code-review",
      name: "Code Review",
      type: "markdown",
      description: "Structured PR / code review with checklist and verdict",
      content: DEFAULT_CODE_REVIEW,
      updatedAt: now,
    },
    {
      id: "adr",
      name: "Architecture Decision Record",
      type: "markdown",
      description: "ADR format for documenting architectural choices",
      content: DEFAULT_ADR,
      updatedAt: now,
    },
    {
      id: "incident-report",
      name: "Incident Report",
      type: "markdown",
      description: "Post-mortem style incident report with timeline and action items",
      content: DEFAULT_INCIDENT_REPORT,
      updatedAt: now,
    },
    {
      id: "prd",
      name: "Product Requirements",
      type: "markdown",
      description: "Product requirements doc with user stories and acceptance criteria",
      content: DEFAULT_PRD,
      updatedAt: now,
    },
    {
      id: "research-summary",
      name: "Research Summary",
      type: "markdown",
      description: "Structured research findings with TL;DR and recommendations",
      content: DEFAULT_RESEARCH_SUMMARY,
      updatedAt: now,
    },
  ];
}

export function getArtifactTemplates(namespaceId: string, orgId: string): ArtifactTemplate[] {
  const filePath = getTemplatesPath(namespaceId, orgId);
  if (!existsSync(filePath)) {
    return getDefaultTemplates();
  }
  try {
    const raw = readFileSync(filePath, "utf-8");
    const data = JSON.parse(raw) as ArtifactTemplatesFile;
    return data.templates;
  } catch {
    return getDefaultTemplates();
  }
}

export function getArtifactTemplate(
  namespaceId: string,
  orgId: string,
  templateId: string
): ArtifactTemplate | null {
  const all = getArtifactTemplates(namespaceId, orgId);
  return all.find((t) => t.id === templateId) ?? null;
}

export function saveArtifactTemplates(
  namespaceId: string,
  orgId: string,
  templates: ArtifactTemplate[]
): void {
  const filePath = getTemplatesPath(namespaceId, orgId);
  const dir = path.dirname(filePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  const data: ArtifactTemplatesFile = { templates };
  writeFileSync(filePath, JSON.stringify(data, null, 2));
}
