import { NextRequest } from "next/server";
import { checkAuth } from "@/lib/auth/api-auth";
import { getNamespaceIdFromRequest, getOrgIdFromRequest } from "@/lib/namespace-config";
import { apiSuccess, withErrorHandling } from "@/lib/api-response";
import { BadRequest, Unauthorized } from "@/lib/api-errors";
import { getProfile } from "@/lib/agents/agent-profile-storage";
import { getWorkspace } from "@/lib/workspaces/workspace-storage";
import { startChainRun } from "@/lib/runs/chain-run-service";
import { ensureSampleChain, getSampleChain, SAMPLE_CHAIN_ID } from "@/lib/onboarding/sample-chain-template";
import { readOnboardingState, writeOnboardingState, nextOperation, CURRENT_SETUP_VERSION, SAMPLE_RUN_DEADLINE_MS } from "@/lib/onboarding/onboarding-state";
import type { Chain } from "@/lib/types";

export const POST = withErrorHandling(async (request: NextRequest) => {
  if (!(await checkAuth(request))) throw new Unauthorized();
  const body = await request.json();
  const profileId = String(body.profileId || "");
  const workspaceId = String(body.workspaceId || "");
  const key = String(body.idempotencyKey || "");
  const setupVersion = Number(body.setupVersion);
  if (!profileId || !workspaceId || !key) throw new BadRequest("profileId, workspaceId and idempotencyKey are required");
  if (setupVersion !== CURRENT_SETUP_VERSION) throw new BadRequest("Unsupported setupVersion", { setupVersion, current: CURRENT_SETUP_VERSION });
  const namespaceId = await getNamespaceIdFromRequest(request);
  const orgId = await getOrgIdFromRequest(request);
  const state = readOnboardingState(namespaceId, orgId);
  if (state.provider.selectedProfileId !== profileId || state.provider.status !== "ready") throw new BadRequest("Profile is not verified for onboarding");
  const profile = getProfile(namespaceId, orgId, profileId);
  const workspace = getWorkspace(namespaceId, orgId, workspaceId);
  if (!profile || !workspace || state.workspace.id !== workspaceId || state.workspace.status !== "ready") throw new BadRequest("Workspace is not ready for onboarding");
  const requestFingerprint = JSON.stringify({ profileId, workspaceId, setupVersion });
  const opResult = nextOperation(namespaceId, orgId, "sample_run", key, "sample-run", requestFingerprint, SAMPLE_RUN_DEADLINE_MS);
  if (opResult.reused && opResult.op.status === "timed_out") throw new BadRequest("Sample run deadline exceeded", { operationId: opResult.op.operationId, errorCode: opResult.op.errorCode });
  if (opResult.reused && "result" in opResult.op && opResult.op.result) return apiSuccess(opResult.op.result);
  ensureSampleChain(namespaceId, orgId);
  const chain: Chain = { ...(getSampleChain() as unknown as Chain), default_agent_profile: profileId };
  const run = await startChainRun({ request, namespaceId, orgId, body: { chain, chainId: SAMPLE_CHAIN_ID, workspaceId, agentProfileId: profileId, userPrompt: "Create a short introduction to Mentiko.", metadata: { source: "onboarding-sample-run" } } });
  const result = { operationId: opResult.op.operationId, status: "in_progress", runId: run.runId, profileId, workspaceId, mutatesWorkspace: false };
  const next = readOnboardingState(namespaceId, orgId);
  next.sampleRun = { status: "in_progress", runId: run.runId, operationId: opResult.op.operationId };
  next.operations[opResult.op.operationId] = { ...opResult.op, result };
  writeOnboardingState(namespaceId, orgId, next, opResult.state.revision);
  return apiSuccess(result);
});
