import { mkdtempSync, rmSync } from "fs";
import os from "os";
import path from "path";
const root=mkdtempSync(path.join(os.tmpdir(),"onb-")); process.env.MENTIKO_GLOBAL_ROOT=root;
import { readOnboardingState, writeOnboardingState, deriveNextAction, nextOperation, READINESS_DEADLINE_MS, CURRENT_SETUP_VERSION } from "./onboarding-state";
describe("onboarding backend state",()=>{ const ns=`test-${Date.now()}-${Math.random().toString(36).slice(2)}`,org="o"; afterAll(()=>rmSync(root,{recursive:true,force:true}));
 it("uses V11 additive defaults and CAS protection",()=>{let s=readOnboardingState(ns,org); expect(CURRENT_SETUP_VERSION).toBe(11); expect(deriveNextAction(s)).toBe("provider"); expect(s.advisorDefaultVerified).toBeUndefined(); s.provider.status="ready"; s=writeOnboardingState(ns,org,s,s.revision); expect(()=>writeOnboardingState(ns,org,s,0)).toThrow("STATE_CONFLICT"); });
 it("deduplicates same fingerprint and records deadline",()=>{const a=nextOperation(ns,org,"provider","k","activation","fp",READINESS_DEADLINE_MS); const b=nextOperation(ns,org,"provider","k","activation","fp",READINESS_DEADLINE_MS); expect(a.op.operationId).toBe(b.op.operationId); expect(a.op.status).toBe("in_progress"); expect(a.op.deadlineAt).toBeTruthy(); expect(b.reused).toBe(true); });
 it("rejects same key with a different fingerprint",()=>{ expect(()=>nextOperation(ns,org,"provider","k","activation","different")).toThrow("IDEMPOTENCY_CONFLICT"); });
 it("does not loop on provider once activated: in_progress (awaiting readiness proof) moves nextAction past provider",()=>{ const s=readOnboardingState(`${ns}-b`,org); s.provider={selectedCli:"claude-code",selectedProfileId:"p1",defaultVerified:true,status:"in_progress"}; expect(deriveNextAction(s)).not.toBe("provider"); expect(deriveNextAction(s)).toBe("project"); });
 it("returns to provider when activation itself needs attention",()=>{ const s=readOnboardingState(`${ns}-c`,org); s.provider={selectedCli:"claude-code",selectedProfileId:"p1",defaultVerified:true,status:"needs_attention"}; expect(deriveNextAction(s)).toBe("provider"); });
});
